### ISSUE TITLE
Aquamacs path

### ISSUE THREAD

**Issue by Drup** [ocaml/tuareg#100]
There seems to be an issue with tuareg installation for old (Yosemite, it seems) OSX version. Tuareg seems to call `Aquamacs/Aquamacs.app`, but this is not executable, and it should call `open -a Aquamacs/Aquamacs.app`.

(I don't have a mac myself, this is second hand on student's systems, sorry if I will not be able to provide more details ...)

**Comment by Chris00** [comment]
Will `open -a ...` also work on recent versions of Mac?

**Comment by Chris00** [comment]
I have pushed a fix.  It would be nice to have a confirmation that it works — I neither have a Mac.  (I'd like to make a release soon.)
