### ISSUE TITLE
tuareg-imenu-create-index is very slow

### ISSUE THREAD

**Issue by moosotc** [ocaml/tuareg#101]
So I had to:
(add-hook 'tuareg-mode-hook
          (function
           (lambda ()
             (load "caml")
             (setq imenu-create-index-function 'caml-create-index-function))))
to have any chance of not losing patience while waiting for imenu while visiting
https://github.com/moosotc/llpp/blob/master/config.ml (or main.ml)

**Comment by Chris00** [comment]
I had a quick look to `caml-create-index-function` and `tuareg-imenu-create-index` (I am not the original author of this) and it is not clear to me that the second one does a better job than the first.  I'll have a deeper look but I may consider dropping the second in favor of the first.

**Comment by Pitometsu** [comment]
Oh, found a workaround for now via `merlin`:

```elisp
(defalias 'tuareg-imenu-create-index 'merlin-imenu-create-index)
```

**Comment by Chris00** [comment]
For imenu (and using the old annot files), Tuareg depends on caml-mode.  This is expressed as a `depopts` in the opam package if you installed Tuareg this way.

**Comment by Pitometsu** [comment]
I installed `tuareg` via https://github.com/dimitri/el-get

Caml package now broken, because refer to https://github.com/ocaml/ocaml/emacs which doesn't exist anymore.

**Comment by Chris00** [comment]
[`caml-mode`](https://github.com/ocaml/caml-mode) has now it [indepdendent repo](https://github.com/ocaml/caml-mode) and the [melpa recipe](https://github.com/melpa/melpa/pull/5966) was updated.

**Comment by Chris00** [comment]
BTW, why use `el-get` instead of the package system that comes with Emacs?

**Comment by Pitometsu** [comment]
Thank you, @Chris00 it will help me fix it. I use el-get because it let me change receipts locally very easy and get latest versions.
