### ISSUE TITLE
Misaligned pipes

### ISSUE THREAD

**Issue by moosotc** [ocaml/tuareg#105]
Tuareg (mis)indents following
```Ocaml
function
| A
  | B -> (* some stuff *)
```
I think pipes should be aligned like they are when A is followed by an arrow.

**Comment by Chris00** [comment]
It is on purpose, see https://github.com/ocaml/tuareg/issues/78

I intend to make it optional but that's low on my priority list — I actually find that it improves readability even though it is not standard.

**Comment by moosotc** [comment]
Christophe Troestler <notifications@github.com> writes:

> It is on purpose, see https://github.com/ocaml/tuareg/issues/78
>
> I intend to make it optional but that's low on my priority list — I
> actually find that it improves readability even though it is not
> standard.

I see, that said, for those unfamiliar with smie rules, is there
anything one can do(put into .emacs) to get the aligned behavior?

No idea what following snippet (referenced in the bug report) actually
means and where to plug it in
(:before "|-or")  ==>  (if (smie-rule-parent-p "|") (smie-rule-parent))

-- 
mailto:moosotc@gmail.com

**Comment by monnier** [comment]
It means to add something like

    (advice-add 'tuareg-smie-rules :before-until
                (lambda (kind token)
                  (and (eq kind :before)
                       (equal token "|-or")
                       (smie-rule-parent-p "|")
                       (smie-rule-parent))))

**Comment by moosotc** [comment]
monnier <notifications@github.com> writes:

> It means to add something like
>
>     (advice-add 'tuareg-smie-rules :before-until
>                 (lambda (kind token)
>                   (and (eq kind :before)
>                        (equal token "|-or")
>                        (smie-rule-parent-p "|")
>                        (smie-rule-parent))))

Thank you!

-- 
mailto:moosotc@gmail.com
