### ISSUE TITLE
Unwanted indentation with bare OCaml expressions

### ISSUE THREAD

**Issue by erikmd** [ocaml/tuareg#106]
When I write bare OCaml expressions (i.e., without binding them to variables) tuareg-mode adds unwanted spaces in front of these expressions.

For example, I get the following indentation, instead of having each line with 0 leading space:
```ocaml
let () = print_endline "A";; (* OK *)
let () = print_endline "B";;
let () = print_endline "C";;
  
  print_endline "D";; (* unexpectedly intended *)
    print_endline "E";;
      print_endline "F";;
```

The issue disappears if I set `tuareg-use-smie` to nil beforehand.

I'm using GNU Emacs 24.4.1 on Debian GNU/Linux with the latest version of tuareg (41ee2e9818ff8573caa160b9d43cf9bb04b1c3b2).

**Comment by Chris00** [comment]
On 2016-11-30, Erik Martin-Dorel wrote:
> 
> When I write bare OCaml expressions (i.e., without binding them to 
> variables) tuareg-mode adds unwanted spaces in front of these 
> expressions.
> 
> For example, I get the following indentation, instead of having each 
> line with 0 leading space:
> ```ocaml
> let () = print_endline "A";; (* OK *)
> let () = print_endline "B";;
> let () = print_endline "C";;
>   
>   print_endline "D";; (* unexpectedly intended *)
>     print_endline "E";;
>       print_endline "F";;
> ```

That's on purpose, you should not write the latter when not in the 
toploop.  The recommended way is:

let () =
  print_endline "A";
  print_endline "B";
  print_endline "C"

**Comment by erikmd** [comment]
Hello @Chris00,
Thanks for your reply. Yes I know that it is bad practice to include bare expressions in the toploop, so indeed this indentation issue should not occur in practice...
Actually I have a specific use case: we are using emacs and tuareg-mode in a functional programming course at Univ. Toulouse 3; for the exercises focusing on OCaml types and expressions in the first lab session, our students backup their expressions (separated with ";;") in a .ml file and use tuareg bindings `C-c C-e` or `C-c C-b` to evaluate them. But due to this indentation behavior the various lines quickly "diverge"...
As a workaround I've tried to do `(setq tuareg-default-indent 0)` but this is unsatisfactory as it would flatten the indentation of code in unrelated situations.
`(setq tuareg-use-smie nil)` would be another possible workaround, but I think it would be a pity not to use the new smie engine.
So I was wondering if a rule saying something like "do not add extra spaces at the beginning of an OCaml phrase" could be implemented within tuareg's smie rules... would you agree with this?
Kind regards.

**Comment by Chris00** [comment]
On 2016-11-30, Erik Martin-Dorel wrote:
> 
> Thanks for your reply. Yes I know that it is bad practice to include 
> bare expressions in the toploop, so indeed this indentation issue 
> should not occur in practice...
> Actually I have a specific use case: we are using emacs and 
> tuareg-mode in a functional programming course at Univ. Toulouse 3; 
> for the exercises focusing on OCaml types and expressions in the first 
> lab session, our students backup their expressions (separated with 
> ";;") in a .ml file and use tuareg bindings `C-c C-e` or `C-c C-b` to 
> evaluate them. But due to this indentation behavior the various lines 
> quickly "diverge"...
> As a workaround I've tried to do `(setq tuareg-default-indent 0)` but 
> this is unsatisfactory as it would flatten the indentation of code in 
> unrelated situations.
> `(setq tuareg-use-smie nil)` would be another possible workaround, but 
> I think it would be a pity not to use the new smie engine.
> So I was wondering if a rule saying something like "do not add extra 
> spaces at the beginning of an OCaml phrase" could be implemented 
> within tuareg's smie rules... would you agree with this?

OK, your use case seems reasonable.  From my experience, it seems to me 
that students do not naturally transition from that style to one where 
the "top expressions" are introduced by "let".  How do you make that 
happen?  Maybe some double semicolons in an .ml file should be 
highlighted specifically?

**Comment by erikmd** [comment]
Hi @Chris00,
> From my experience, it seems to me that students do not naturally transition from that style to one where the "top expressions" are introduced by "let". How do you make that happen? Maybe some double semicolons in an .ml file should be highlighted specifically?

Regarding the teaching units on OCaml I am involved in, we have a strong focus on functional programming and avoid dealing with imperative constructs whenever possible; so most "top expressions" we consider in the exercises I was mentioning won't have type unit... and thereby when we introduce the notion of environment the students naturally think in terms of global definitions.

However, I understand your concern about making sure that there is some "hint" somewhere, to tell the user not to use a bare top expression but rather start his/her "effectful" phrase with `let _ =` or better with `let () =`.
I like your suggestion of highlighting the ";;" e.g. the one that immediately follows the phrase at stake, but I don't know how easy it is to implement such a warning.
Otherwise, maybe you could just update the indentation rule in tuareg-mode, and the warning itself could be implemented in [Merlin](https://github.com/the-lambda-church/merlin) and/or [Flycheck](https://github.com/flycheck/flycheck-ocaml) ?
Kind regards.
