### ISSUE TITLE
infix symbol ( << ) parsed as syntax-quotation

### ISSUE THREAD

**Issue by jpathy** [ocaml/tuareg#107]
Hello,
I have some infix functions defined which have two or more '<' symbol but tuareg parses them as syntax-quotation (camlp4). e.g. ` let ( << ) = (lsl) let _ = 10 << 2`
(new to emacs and elisp so not sure how to fix it yet).

Currently i have `(fmakunbound 'syntax-propertize-rules)` to disable quotation extension.

**Comment by Chris00** [comment]
At the same time, camlp4 is still used.  Maybe we should turn this feature into a minor mode?

**Comment by jpathy** [comment]
Indeed it would be helpful to separate camlp4 extension from lang syntax.

**Comment by Chris00** [comment]
Fixed in https://github.com/ocaml/tuareg/commit/207d7f6b77893a3656259ead63d66c2f780d410e

PPX basically replaced Camlp4 so syntax highlighting for quotations has been removed.
