### ISSUE TITLE
tuareg-smie--inside-string moves the point

### ISSUE THREAD

**Issue by Chris00** [ocaml/tuareg#114]
@monnier The documentation of `smie-indent-functions` says that its functions _shouldn’t move point_.  `tuareg-smie--inside-string` does move the point however.  Does not seem to be a problem but I am not sure whether this is future proof.

While we are at it, `tuareg-smie--args` says it is mostly copy & pasted from SMIE.  Can we get rid of it for Emacs 25?  (This is not urgent anyway because some backward compatibility code will need to stay in place.)

**Comment by monnier** [comment]
Regarding `tuareg-smie--inside-string`, it's probably an oversight that's trivially fixed by `save-excursion`.

Regarding `tuareg-smie--args`, SMIE still doesn't have any hooks to do that cleanly, no.  Help welcome ;-)

**Comment by Chris00** [comment]
Thanks for the prompt answer.
