### ISSUE TITLE
Symbol's function definition is void: tuareg-skip-blank-and-comments

### ISSUE THREAD

**Issue by diml** [ocaml/tuareg#115]
Commit 04f835f4dd69c7292a20666aeb4b9b9535880150 breaks utop.el (cf https://github.com/diml/utop/issues/195) as it renames `tuareg-skip-blank-and-comments` to `tuareg--skip-blank-and-comments` . Any reason this function was renamed?

**Comment by Chris00** [comment]
It is because I saw it as an internal function.  I will revert it back.

**Comment by diml** [comment]
Thanks!
