### ISSUE TITLE
narrow-to-defun behaviour?

### ISSUE THREAD

**Issue by mookid** [ocaml/tuareg#118]
`narrow-to-defun` is a function that narrows the view of the current buffer to the current top level definition (see [the doc](https://www.gnu.org/software/emacs/manual/html_node/emacs/Narrowing.html)).

narrowing is a convenient way of using more safely function such as `query-replace-regexp`.

However, it is unfortunately useless in tuareg, because it is specialized to lisp code. Is it possible to teach this function how to parse OCaml top-level definitions?

**Comment by Chris00** [comment]
I agree that would be useful.  I'll try to work on that when I'll get some time.  (Of course, feel also free to submit a PR!)

**Comment by mookid** [comment]
I'll try to take a look this weekend.

**Comment by Chris00** [comment]
@mookid There is `tuareg-narrow-to-phrase` — is it enough for you?

**Comment by mookid** [comment]
@Chris00 I am not user anymore.
