### ISSUE TITLE
I think we should change AQUAMACS variable to /Applications/Aquamacs.app/Contents/MacOS/Aquamacs in the makefile

### ISSUE THREAD

**Issue by zraibi** [ocaml/tuareg#119]

**Comment by Chris00** [comment]
I do not have a Mac so I have no idea what the right path is.  Is there a portable way to discover it such as `which Aquamacs`?

**Comment by zraibi** [comment]
There is no default link to Aquamacs binary file. I'm trying to install tuareg with opam in Mac, and it's OK for GNU Emacs, but it raise this make error for Aquamacs:
`### stderr ###
# /bin/sh: /Applications/Aquamacs.app: is a directory
# make: *** [tuareg-site-file.el] Error 126`

**Comment by Chris00** [comment]
> There is no default link to Aquamacs binary file.

OK but is there a way to determine it?

**Comment by zraibi** [comment]
Aquamacs binary file path is always in /Applications/Aquamacs.app/Contents/MacOS/Aquamacs, or determine it with find command: `find /Applications -type f | grep 'Aquamacs$'`, and we'll have to replace EMACS variable in:
```
ifeq ($(wildcard $(AQUAMACS)),$(AQUAMACS))
EMACS ?= open -a $(AQUAMACS)
```
to:
EMACS ?= $(AQUAMACS)

**Comment by monnier** [comment]
Why do you run the makefile?  I mean, why don't you install it via ELPA?  ELPA doesn't have this problem because it's run by Emacs, so it doesn't have to look for an Emacs executable.

**Comment by Chris00** [comment]
Tuareg is also available through [opam](https://opam.ocaml.org/) because it is where OCaml users expect to find tools.  It is also (automatically) made available through MELPA.

**Comment by retnuh** [comment]
I've just run into this problem too, trying to install via opam (which is what the github page recommends as best way to install).

**Comment by Chris00** [comment]
A release [is ongoing](https://github.com/ocaml/opam-repository/pull/10652).  It should fix the problem.
