### ISSUE TITLE
Indentation of ;%ext

### ISSUE THREAD

**Issue by Chris00** [ocaml/tuareg#121]
The code
```ocaml
let () =
  a;
  b
```
and
```ocaml
let () =
  a;%ext
  b
```
should be indented exactly in the same way (as above).  Currently, the latter is indented as
```ocaml
let () =
  a;%ext
    b
```

**Comment by Chris00** [comment]
@monnier If you have a bit of time, you help will be appreciated on this one.  Is defining a token `;%…` the way to go?

**Comment by monnier** [comment]
> @monnier If you have a bit of time, you help will be appreciated on this
> one.  Is defining a token `;%…` the way to go?

Can you point me to the documentation explaining the syntax rules and
semantics of this thing?

**Comment by Chris00** [comment]
On 12 April 2019 at 02:48 CEST, monnier wrote:
>
>> @monnier If you have a bit of time, you help will be appreciated on
>> this one. Is defining a token `;%…` the way to go?
>
> Can you point me to the documentation explaining the syntax rules and
> semantics of this thing?

These are extension nodes in infix form:
https://caml.inria.fr/pub/docs/manual-ocaml-4.07/extn.html#sec262
In this case, this is

  ;%⟨attr-id⟩

Where ⟨attr-id⟩ is defined as:

  attr-id ::= lowercase-ident  
           ∣  capitalized-ident  
           ∣  attr-id .  attr-id  

https://caml.inria.fr/pub/docs/manual-ocaml-4.07/extn.html#attr-id

**Comment by monnier** [comment]
I just pushed a patch which should fix it.

**Comment by Chris00** [comment]
Thanks!
