### ISSUE TITLE
Is tuareg compatible with ReasonML ?

### ISSUE THREAD

**Issue by arichiardi** [ocaml/tuareg#125]
Hello folks!

I was wondering if there are assumptions regarding the syntax (there probably are) and how difficult would be to hook a custom parser/conversion stop from Reason by Facebook.
The reason (pun intended) I am asking is that there is very minimal support for the repl integration in emacs ([editor configuration page](http://facebook.github.io/reason/tools.html#editor-integration)), whereas there exists an `rtop -emacs` in there, however I do not know how to communicate with it.

```
> ReasonProject@0.0.1 env /home/arichiardi/git/ReasonProject
> eval $(dependencyEnv) && env "rtop" "-emacs"

phrase-terminator:;;
stdout:Welcome to utop version 1.19.2 (using OCaml version 4.02.3)!
stdout:
phrase-terminator:;
stderr:Reason: Meta Language Utility
stdout:Exception: Assert_failure ("src/reason_util.ml", 16, 4).
prompt:
```

I am also an OCaml newbie (but not an elisp one) that would like to get his hands dirty so any pointers are appreciated.

**Comment by arichiardi** [comment]
I have noticed that given the different syntax a phrase in Tuareg is not the same as a phrase in ReasonML.
So a corollary question here would be, is there a way for tuareg to undrestand ReasonML syntax?

**Comment by Chris00** [comment]
You probably can reuse part of the SMIE configuration.  It is not clear to me whether the changes would be small enough to consider parametrizing it.  Maybe you can start the work of adapting Tuareg to Reason in a separate branch and then we see wether the two can be merged together (or whether we add a separate tuareg-reason file is needed)?

**Comment by arichiardi** [comment]
The other thing to consider is that in reason there is a tool for reformatting called `refmt`, so probably I'd need only a subset of the smie grammar. In any case I will try to put something together. Probably a separate file or something, and write then here. I also really like utop and reason comes with an rtop repl.
The file that communicates with it is `utop.el` in the utop GitHub repo and I might just need to make that one understand reason's grammar

**Comment by Chris00** [comment]
On 2017-04-13, Andrea Richiardi wrote: 
> 
> The other thing to consider is that in reason there is a tool for 
> reformatting called refmt, so probably I'd need only a subset of the 
> smie grammar.
 
Sure but it will be more convenient to the users if Emacs automatic 
formatting is close — or identical — to what refmt does. 

> In any case I will try to put something together. Probably a separate file or something, and write then here.

Great.

**Comment by Chris00** [comment]
Feel free to propose a PR or reopen this issue when your investigations bear some fruit.
