### ISSUE TITLE
Explanation to disable the electric-indent-mode is not correct for Emacs 25.1.1

### ISSUE THREAD

**Issue by camlspotter** [ocaml/tuareg#128]
The document says:

```
Emacs ≥ 24.4 turned on electric-indent-mode mode by default. If you do not like it, call (electric-indent-mode 0) in tuareg-mode-hook.
```
But it does not work for Emacs 25.1.1.  I use the following hook to disable the `electric-indent-mode`:
```
      (add-hook
       'tuareg-mode-hook
       ;; Turn on auto-fill minor mode.
       (lambda ()
          (set (make-local-variable 'electric-indent-mode) nil)))))
```

**Comment by Chris00** [comment]
The documentation of the VARIABLE ‘electric-indent-mode‘ says

  Setting this variable directly does not take effect;
  either customize it (see the info node ‘Easy Customization’)
  or call the function ‘electric-indent-mode’.

Please use the FUNCTION as recommended (if it still does not work for 
you, please let us know).

**Comment by Chris00** [comment]
No further comment.  I assume the problem is resolved.
