### ISSUE TITLE
Types of function parameters don't change colors if there isn't a space between : and the type

### ISSUE THREAD

**Issue by hydrocat** [ocaml/tuareg#129]
to test, write :
```ocaml
let f (intlist:int list) = ()
```
however it works when there is a space, for example:
```ocaml
let f (intlist: int list) = ()
```

**Comment by hydrocat** [comment]
to test, write :
```ocaml
let f (intlist:int list) = ()
```
however it works when there is a space, for example:
```ocaml
let f (intlist: int list) = ()
```

**Comment by Chris00** [comment]
A space was required to avoid wrong syntax highlighting of 
```ocaml
(f ~label:v x y)
```
v.s.
```ocaml
(f label:v x y)
```
but I'll try to come up with a better regexp.

**Comment by hydrocat** [comment]
Can you point me to where the regex is ? I'd like to mess with it a little :)

**Comment by Chris00** [comment]
https://github.com/ocaml/tuareg/blob/master/tuareg.el#L965-L974
