### ISSUE TITLE
Indent of match clause is wrong when it is the first clause and the first pipe is omitted.

### ISSUE THREAD

**Issue by loloiccl** [ocaml/tuareg#130]
Although when we omit the first pipe of match patterns we expected the code indent as follows,
```
let command () =
  match x with
    A ->
     a
  | B ->
     b
```

the code is actually indented as follows.
```
let command () =
  match x with
    A ->
    a
  | B ->
     b
```

Note indent of the line "a"  and the indent of the line "A ->" are the same.
The indent of the line "a" should be the same as the indent of the line "b".

**Comment by Chris00** [comment]
Thanks for reporting.

**Comment by loloiccl** [comment]
You are welcome.
Thanks for fixing!
