### ISSUE TITLE
Errors with 'tuareg-eval-phrase' on the FIRST line of the file

### ISSUE THREAD

**Issue by Fourchaux** [ocaml/tuareg#135]
OCaml 4.04.1+flambda & Spacemacs & Linux & Merlin 3.0.0

Funny things happen if the FIRST character of a file is a number:

1+2 ;; cursor before ' + ' then ``` tuareg-eval-phrase ```  -> int = 1 ??
1+2 ;; cursor after  ' + '   then ``` tuareg-eval-phrase ``` -> int = 2 ??

Also :
1 * 2 ;; cursor before ' * ' then ``` tuareg-eval-phrase ``` -> int = 1 ??
1 * 2 ;; cursor after  ' * ' then  ``` tuareg-eval-phrase ```  ->
*2
^
Error: Syntax error

With e.g. :
(1+2) ;; -> int = 3 : OK

**Note:**
Issue https://github.com/ocaml/tuareg/issues/126 also present here.

**Comment by erikmd** [comment]
Hi, I use OCaml 4.02.3 and tuareg master under GNU/Linux and it seems that beyond your example of infix operators, this issue with `tuareg-eval-phrase` also occurs for prefix operators (see example below), *but only for the first line of the file:*

```ocaml
print_endline "Line 1";; (* cursor at begin → C-c C-e Fails → "- : string -> unit = <fun>" *)
print_endline "Line 2";; (* C-e C-e works → "Line 2- : unit = ()" *)
```

**Comment by Fourchaux** [comment]
@erikmd 
```
print_string "Line 1";;
```
Same issue here. The first line is doomed  ...

**Comment by Chris00** [comment]
I'll try to improve it but note that you should write `let _ = 1 + 2` to be "phrase" and not an expression.
