### ISSUE TITLE
Mac os-x => M-x  run-ocaml  [no match]

### ISSUE THREAD

**Issue by fredOnGitHub** [ocaml/tuareg#137]
version mac 10.12.6

Hello 
i have a fresh installation of emacs with tuareg

I have done 

brew install emacs --with-cocoa
opam --version
      1.2.2
opam install tuareg
emacs a.ml &

i do  M-x  with key and i write run-ocaml 
to see
M-x  run-ocaml 
and i press enter Keyboard Key

and i see [no match]

it is the seem with 
M-x  tuareg-mode

also i have

C-c C-e is undefined

Thanks

**Comment by Chris00** [comment]
> ```
> opam install tuareg
> emacs a.ml &
> ```

Did you perform the `load` step displayed on the terminal at the end of the `opam install` step (see also the [README](https://github.com/ocaml/tuareg#install))?

**Comment by fredOnGitHub** [comment]
Hello,
I haven't performed the step displayed
I did i new installation to get this message

=-=- tuareg.2.0.10 installed successfully -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫 
=> If you have not yet done so, please add in ~/.emacs.d/init.el or
   in ~/.emacs to following line:
       (load "/Users/********/.opam/system/share/emacs/site-lisp/tuareg-site-file")
   You should consider installing "merlin" (completion, displaying types,...)
   or "caml-mode" (displaying types).

There hasn't .emacs.d/init.el so i 've done
nano .emacs.d/init.el 

and wrote the load indicated by the installation 
load "/Users/********/.opam/system/share/emacs/site-lisp/tuareg-site-file"

and stat again 
emacs a.ml &

and the same thing, doing M-x with key and i write run-ocaml
to see
M-x run-ocaml
and pressing enter Keyboard Key

I see 
M-x ocaml-run[no match]

**Comment by Chris00** [comment]
>  nano .emacs.d/init.el

Why didn't you do it with Emacs?

> ` load "/Users/********/.opam/system/share/emacs/site-lisp/tuareg-site-file"`

Parentheses are required, as shown on the post-install message.

Can you confirm you do not have an `~/.emacs` file?  (If you do, move its content to `~/.emacs.d/init.el` and erase it.)

**Comment by fredOnGitHub** [comment]
Hello,

that's ok now

yes i have put the required Parentheses with emacs,
(load "/Users/********/.opam/system/share/emacs/site-lisp/tuareg-site-file")

i didn't have a ~/.emacs file 

My problem is resolved 

Thank You very much

**Comment by Chris00** [comment]
For other persons stumbling on this bug, could you tell what was the problem?

**Comment by fredOnGitHub** [comment]
If you put 
load "/Users/********/.opam/system/share/emacs/site-lisp/tuareg-site-file" (in my case)
like the installation suggested it doesn't work
you get M-x run-ocaml[no match]
you have to put exactly M-x run-ocaml[no match]
(load "/Users/********/.opam/system/share/emacs/site-lisp/tuareg-site-file") with parenthesis
(in my case)
