### ISSUE TITLE
Switch to .mll from .mli file doesn't work.

### ISSUE THREAD

**Issue by rgrinberg** [ocaml/tuareg#140]
Create 2 files in the same directory: x.mli and x.mll. I'd expect `tuareg-find-alternate-file` to toggle between them. But that only works in one way (mll -> mli). When the .mli file is open, tuareg can't figure out that the alternate file is the .mll file and attempts to open a new x.ml file.

**Comment by Chris00** [comment]
Well `.mll` → `mli` works, it is `.mli` → `.mll` that does not.

**Comment by rgrinberg** [comment]
Yeah, that is why I meant. Perhaps my report was confusing. It would be best if it worked both ways though :)

**Comment by rgrinberg** [comment]
Thank you for the very prompt fix

**Comment by Chris00** [comment]
@rgrinberg BTW, may you test the new — basic — mode to edit opam files and let me know what you think?

**Comment by rgrinberg** [comment]
Sure, I'll give it a try. Just to clarify, is this an alternative to: https://github.com/sagotch/opam-mode.el

**Comment by Chris00** [comment]
Did not know about that one.  It does not seem to do much — in particular, no indentation which is what I was after.  Also, OPAM "url" files are not covered because my opinion is that one should not write these by hand.
