### ISSUE TITLE
Improving jbuilder support

### ISSUE THREAD

**Issue by rgrinberg** [ocaml/tuareg#141]
I see that tuareg now has some elementary support for jbuilder - sweet! I'm very pleased to see that there's interest in jbuilder and I'd like to expand on this initial support. Some ideas/notes/questions I have in mind:

* jbuild files should have their own major mode (derived off lisp or scheme)
* Why did you choose lisp over scheme mode for jbuilder? Some janestreet users said that they used scheme mode, but I'm not sure what's the difference here anyway.
* change the default indentation to 1 space. That seems to be the standard for all jbuild files out there.
* support jbuild stanza keywords
* support the special multiline comment syntax
* Add some sort of linting support with flycheck/flymake. This might require a little support from jbuilder itself but it should be a fairly rudimentary change.

What do you think?

**Comment by Chris00** [comment]
On 2017-08-22, Rudi Grinberg wrote: 
> 
> * jbuild files should have their own major mode (derived off lisp or 
> scheme) 

That’s the case — the mode is just part of the Tuareg package.

> * Why did you choose lisp over scheme mode for jbuilder? Some janestreet users said that they used scheme mode, but I'm not sure what's the difference here anyway.

Don’t know the differences either — changed to scheme.

> * change the default indentation to 1 space. That seems to be the standard for all jbuild files out there.

Done.

> * support jbuild stanza keywords

Not sure what you mean.  There is already syntax highlighting of these.

> * support the special multiline comment syntax
> * Add some sort of linting support with flycheck/flymake. This might require a littlesupport from jbuilder itself but it should be a fairly rudimentary change.

This will come later.

**Comment by rgrinberg** [comment]
OK, this is excellent. I think I just don't have the most up to date version from melpa.

Great work!

**Comment by rgrinberg** [comment]
@Chris00 Would you mind updating the skeletons to use 1 space for indentation?

**Comment by Chris00** [comment]
On 2017-08-23, Rudi Grinberg wrote:
> 
> @Chris00 Would you mind updating the skeletons to use 1 space for 
> indentation?

Done

**Comment by bcc32** [comment]
I think the skeletons need an extra pair of parentheses in both the `library` and the `executables` rule, e.g.:

```
(executables
 (names        ())
 (public_names ())
 (libraries ()))
```

should be:

```
(executables
 ((names        ())
  (public_names ())
  (libraries ())))
```

**Comment by Chris00** [comment]
@bcc32 You are right.  Fixed in e6eff8e.

**Comment by Chris00** [comment]
For Flymake, I'll wait until [jbuilder lint](https://github.com/janestreet/jbuilder/issues/241) is in place.

**Comment by Chris00** [comment]
In commit 1d0058a is some support for linting.  If you want to try it, set `tuareg-jbuild-flymake` and add to your path the executable script `jbuilder-lint` with content (say):
```ocaml
#!/usr/bin/env ocaml
;;
#load "unix.cma";;
#load "str.cma";;

open Printf

let filename = Sys.argv.(1)

let read_all fh =
  let buf = Buffer.create 1024 in
  let b = Bytes.create 1024 in
  let len = ref 0 in
  while len := input fh b 0 1024; !len > 0 do
    Buffer.add_subbytes buf b 0 !len
  done;
  Buffer.contents buf

let errors =
  let cmd = sprintf "jbuilder external-lib-deps \
                     --root=%s %s"
              (Filename.quote (Filename.dirname filename))
              (Filename.quote (Filename.basename filename)) in
  let env = Unix.environment() in
  let (_,_,fh) as p = Unix.open_process_full cmd env in
  let out = read_all fh in
  match Unix.close_process_full p with
  | Unix.WEXITED (0|1) ->
     (* jbuilder will normally exit with 1 as it will not be able to
        perform the requested action. *)
     out
  | Unix.WEXITED 127 -> printf "jbuilder not found in path.\n"; exit 1
  | Unix.WEXITED n -> printf "jbuilder exited with status %d.\n" n; exit 1
  | Unix.WSIGNALED n -> printf "jbuilder was killed by signal %d.\n" n; exit 1
  | Unix.WSTOPPED n -> printf "jbuilder was stopped by signal %d\n." n; exit 1


let () =
  let re = "\\(:?\\)[\r\n]+\\([a-zA-Z]+\\)" in
  let errors = Str.global_substitute (Str.regexp re)
                 (fun s -> let colon = Str.matched_group 1 s = ":" in
                           let f = Str.matched_group 2 s in
                           if f = "File" then "\n File"
                           else if colon then ": " ^ f
                           else ", " ^ f)
                 errors in
  print_string errors


;;
(* Local Variables: *)
(* mode: tuareg *)
(* End: *)
```

**Comment by Chris00** [comment]
Something better should be done because jbuilder lacks context with this method and issues spurious errors...

**Comment by Chris00** [comment]
Linting support with flymake is implemented — but not activated by default, do `(setq tuareg-jbuild-flymake t)` — the script above being generated on the fly.  Opam files are also copied to provide context.  Please test and report problems.
