### ISSUE TITLE
Font-lock failure on "<<" operator

### ISSUE THREAD

**Issue by coventry** [ocaml/tuareg#142]
Under emacs version 26.0.50 and a fresh checkout of tuareg (commit 1549cd), the `<<` operator in [this OCaml file](https://github.com/tezos/tezos/blob/c091add3352cf6563d2a46bdc4196dd402cf226d/src/minutils/utils.ml#L197) causes the rest of the file to be rendered in `font-lock-preprocessor-face`.

![emacs](https://user-images.githubusercontent.com/70152/29638642-dd5507de-8825-11e7-8654-58fac105aab8.png)

**Comment by Chris00** [comment]
`<< ... >>` were used by camlp4 for quotations.  Maybe it is time to remove their special handling.

**Comment by coventry** [comment]
Thank you!
