### ISSUE TITLE
warning when compiling tuareg varsion 2.1.0 in emacs 25.2.1

### ISSUE THREAD

**Issue by yogin25** [ocaml/tuareg#144]
I got warnings in my compile-log after updating tuareg to the latest version from melpa

I would like to share them with you to give more insight on what happening.

tuareg-opam.el:101:7:Warning: assignment to free variable
    ‘tuareg-opam-smie-grammar’

In verbose-tuareg-opam-smie-rules:
tuareg-opam.el:147:21:Warning: reference to free variable ‘smie--parent’

Compiling file /home/zakaria/.emacs.d/elpa/tuareg-20170823.806/tuareg-site-file.el at Fri Aug 25 13:55:02 2017

Compiling file /home/zakaria/.emacs.d/elpa/tuareg-20170823.806/tuareg.el at Fri Aug 25 13:55:02 2017

In tuareg-smie-rules:
tuareg.el:1885:24:Warning: reference to free variable ‘smie--parent’

Compiling file /home/zakaria/.emacs.d/elpa/tuareg-20170823.806/tuareg_indent.el at Fri Aug 25 13:55:02 2017

In tuareg-compute-normal-indent:
tuareg_indent.el:1445:35:Warning: reference to free variable
    ‘tuareg-definitions-regexp’

In tuareg-next-phrase:
tuareg_indent.el:1951:24:Warning: tuareg-discover-phrase called with 2
    arguments, but accepts only 0

In end of data:
tuareg_indent.el:2049:1:Warning: the following functions are not known to be defined:
    tuareg-reset-and-kwop, tuareg-interactive-end-of-phrase.

I have to highlight the fact that i received other warnings from from the caml.el compilation, i'll post them as a complement of information:

.emacs.d/elpa/caml-20151009.845/caml.elc:Warning: Use ‘with-current-buffer’
    rather than save-excursion+set-buffer
.emacs.d/elpa/caml-20151009.845/caml.elc:Warning: ‘next-line’ is for
    interactive use only; use ‘forward-line’ instead.
Leaving directory ‘/home/zakaria/.emacs.d/elpa/tuareg-20170823.806’

Compiling file /home/zakaria/.emacs.d/elpa/tuareg-20170823.806/dot-emacs.el at Fri Aug 25 13:55:01 2017
Entering directory ‘/home/zakaria/.emacs.d/elpa/tuareg-20170823.806/’

Compiling file /home/zakaria/.emacs.d/elpa/tuareg-20170823.806/ocamldebug.el at Fri Aug 25 13:55:01 2017
ocamldebug.el:82:41:Warning: ‘set-face-underline-p’ is an obsolete function
    (as of 24.3); use ‘set-face-underline’ instead.

In ocamldebug-complete:
ocamldebug.el:435:6:Warning: ‘comint-dynamic-simple-complete’ is an obsolete
    function (as of 24.1); use ‘completion-in-region’ instead.

Best regards

**Comment by hannesm** [comment]
`caml.el` from the OCaml distribution fixed warnings in https://github.com/ocaml/ocaml/pull/1296 AFAICT

**Comment by yogin25** [comment]
thank's @hannesm

**Comment by yogin25** [comment]
I just updated tuareg from melp and i get other set of warnings:

here is the output, i hope that will be helpfull

ocamldebug.el:82:41:Warning: ‘set-face-underline-p’ is an obsolete function
    (as of 24.3); use ‘set-face-underline’ instead.

In ocamldebug-complete:
ocamldebug.el:435:6:Warning: ‘comint-dynamic-simple-complete’ is an obsolete
    function (as of 24.1); use ‘completion-in-region’ instead.

Compiling file /home/zakaria/.emacs.d/elpa/tuareg-20170904.831/tuareg-jbuild.el at Tue Sep  5 00:46:48 2017

Compiling file /home/zakaria/.emacs.d/elpa/tuareg-20170904.831/tuareg-light.el at Tue Sep  5 00:46:48 2017

Compiling file /home/zakaria/.emacs.d/elpa/tuareg-20170904.831/tuareg-opam.el at Tue Sep  5 00:46:48 2017
tuareg-opam.el:127:7:Warning: assignment to free variable
    ‘tuareg-opam-smie-grammar’

In verbose-tuareg-opam-smie-rules:
tuareg-opam.el:173:21:Warning: reference to free variable ‘smie--parent’

In tuareg-opam-mode:
tuareg-opam.el:189:15:Warning: reference to free variable
    ‘tuareg-opam-smie-grammar’

In tuareg-smie-rules:
tuareg.el:1885:24:Warning: reference to free variable ‘smie--parent’

Compiling file /home/zakaria/.emacs.d/elpa/tuareg-20170904.831/tuareg_indent.el at Tue Sep  5 00:46:49 2017

In tuareg-compute-normal-indent:
tuareg_indent.el:1445:35:Warning: reference to free variable
    ‘tuareg-definitions-regexp’

In tuareg-next-phrase:
tuareg_indent.el:1951:24:Warning: tuareg-discover-phrase called with 2
    arguments, but accepts only 0

In end of data:
tuareg_indent.el:2049:1:Warning: the following functions are not known to be defined:
    tuareg-reset-and-kwop, tuareg-interactive-end-of-phrase

**Comment by Chris00** [comment]
Commit https://github.com/ocaml/tuareg/commit/459f05ce46526235e6c3e949c84805f659a1cb80 fixed some warnings.

**Comment by Chris00** [comment]
The only warning remaining is
```
tuareg.el:1771:24:Warning: reference to free variable ‘smie--parent’
```
but it will stay for now.
