### ISSUE TITLE
Tuareg asks about abbreviations when trying to save a file

### ISSUE THREAD

**Issue by bschommer** [ocaml/tuareg#146]
Whenever I try to close an ocaml file I get asked whether I want to save my abbrevs. I'm using the latest  version of tuarge tuareg-20170906.2344.

**Comment by Chris00** [comment]
What is your value of `tuareg-use-abbrev-mode`?

**Comment by Chris00** [comment]
It is still worth answering the above question but to solve your problem, set `(setq save-abbrevs 'silently)` in your Emacs init file.

**Comment by Chris00** [comment]
See also https://github.com/syl20bnr/spacemacs/issues/9450

**Comment by Fourchaux** [comment]
**Note:** same message here.

Using ```(setq save-abbrevs 'silently)``` solve this problem 
(tested with 'vanilla' Emacs v25.3 AND Spacemacs)

**Comment by monnier** [comment]
I just installed fix for this problem.  The real cause is in caml.el (i.e. outside of tuareg).

**Comment by gasche** [comment]
Note: I just merged @monnier's patch upstream

  https://github.com/ocaml/ocaml/commit/48936edfbb104ca26d988150e827e6f65e70e753
