### ISSUE TITLE
tuareg-support-metaocaml does not highlight MetaOCaml staging annotations

### ISSUE THREAD

**Issue by aschaap** [ocaml/tuareg#151]
I'm pretty new to emacs, but have been using MetaOCaml for a while.

I installed opam 1.3.1-r1 and emacs 25.2 through my distribution's package manager (portage). I subsequently installed BER MetaOCaml 4.04.0+BER and tuareg 2.0.10 via opam (in that order). I've edited .emacs to add the following line: `(load "/home/user/.opam/4.04.0+BER/share/emacs/site-lisp/tuareg-site-file")`, and `(setq tuareg-support-metaocaml t)` as suggested by http://okmij.org/ftp/ML/MetaOCaml.html. However, when I load a file containing staging annotations, they are not highlighted in any way (see attached pictures). The font lock for multistage is untouched, and it appears staging annotations should be darkblue on lightgray. 

I've previously tried this on the Linux Subsystem for Windows (which seems to be plain Ubuntu without Xorg) on a different machine with both BER MetaOCaml 4.02.1+BER and 4.04.0+BER, using opam's tuareg 2.0.10 and it's user-setup package to configure emacs for me and setting tuareg-support-metaocaml using M-x customize. This produced the same seemingly unsatisfactory result as shown in the attached screenshots.

Is there anything I should (or shouldn't) have done to get this working, or am I misunderstanding the intended behaviour?

Thank you in advance.

![image](https://user-images.githubusercontent.com/8865084/31586527-46c9f4ce-b1a0-11e7-872e-08e597b39790.png)

![image](https://user-images.githubusercontent.com/8865084/31586577-dcf36930-b1a0-11e7-8a55-d6c8e9820e78.png)

**Comment by Chris00** [comment]
I have not found it in the documentation but it seems that `<.<` is an operator but `>.>` is interpreted as `>. >`.

**Comment by Chris00** [comment]
It seems the manual often mistype `!.` for `.!`, right?
