### ISSUE TITLE
Only prompt for jbuild skeleton on empty buffer

### ISSUE THREAD

**Issue by bcc32** [ocaml/tuareg#153]
If `tuareg-jbuild` mode is activated in a buffer that doesn't correspond to a file (e.g., code source blocks in org-mode, mmm-mode, etc.), it _always_ prompts for whether or not to fill the file with a skeleton, even if the buffer already contains a valid jbuild configuration. Is it possible to only activate this feature when the buffer is empty?

**Comment by Chris00** [comment]
Could you please test the current Git version and tell whether it fixes your problem?

**Comment by bcc32** [comment]
Thanks for the quick response. The issue is fixed for editing code blocks (thanks!), although I still get the prompt when I try to export from Org mode. I think this might be just a quirk of the way Org mode does exporting, and I'm not sure there's really a good solution to this.

**Comment by Chris00** [comment]
I think the better is _not_ to automatically propose to fill an empty buffer with a skeleton but to provide a menu with various templates.

**Comment by Chris00** [comment]
I used skeletons.  That should fix the issue in all cases.
