### ISSUE TITLE
tuareg has cyclic dependency with user-setup

### ISSUE THREAD

**Issue by hanjiexi** [ocaml/tuareg#155]
I already have tuareg installed in OCaml 4.06.0, and attempted to install user-setup. Here's what happened:
```bash
$ opam install user-setup
The actions to process have cyclic dependencies:
  - ∗  tuareg.2.1.0 -> ∗  user-setup.0.6 -> ∗  tuareg.2.1.0

No solution found, exiting
```
I also have both tuareg and user-setup installed already in OCaml 4.05.0, but `opam upgrade` is failing because of the same error as above.

**Comment by Chris00** [comment]
Waiting for https://github.com/ocaml/opam-repository/pull/10683 to be merged.
