### ISSUE TITLE
Wish: make new extension point highlighting optional

### ISSUE THREAD

**Issue by jberdine** [ocaml/tuareg#156]
Perhaps this situation is uncommon, but I work with code where extensions are better highlighted as regular code. For example,
```
[%Trace.call fun pf -> pf "%a" fmt_foo foo]
```
is interpreted by a ppx rewriter that knows about `Trace.call` and treats the argument of the extension point as a closure. This sort of case is much better highlighted as regular code than in a single face. Also, from the perspective of the underlying parsetree, the argument of the extension point identifier is an arbitrary expression. It would be informative enough to e.g. set `[%` and `]` in a specific, likely high-attention, face.

**Comment by Chris00** [comment]
I will do it as follows:
![extension](https://user-images.githubusercontent.com/1255665/45571765-983bd380-b867-11e8-82dd-1c40880b8280.png)
