### ISSUE TITLE
$ opam user-setup install dont works

### ISSUE THREAD

**Issue by cakebytheoceanLuo** [ocaml/tuareg#157]
I want to use merlin, utop, tuareg (ocaml things) on my emacs. But when i give opam the following code, the emacs setting doesnot work, instead come many issues. Do anyone have some idea?

```
Administrator@USER-6FNCH9N4V0 ~
$ opam user-setup install
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
```

**Comment by Chris00** [comment]
I think it would be better to report the problem to user-setup — I do not use it so don't know what the problem is.
