### ISSUE TITLE
Cannot send empty commands to OCaml REPL

### ISSUE THREAD

**Issue by ysalmon** [ocaml/tuareg#158]
I have just installed a fresh opam, emacs, ocaml, and tuareg setup in a virtual machine and I experience an odd behaviour when evaluating a phrase.

Typing in a blank .ml file
```
let x = 42;;
```
and hitting C-x C-e leads to an error : Cannot send empty commands to OCaml REPL!.
This appears to happen because the text cursor is just after the second ```;```. Setting the text cursor before the first ```;``` and hitting C-x C-e leads to a correct evaluation.

However, this is at odds with the behaviour of tuareg on my main system, which is : evaluating the phrase just before ```;;``` if the text cursor is just after such a construct.

While I reckon this new behaviour allows for improvement when multiple phrases are on the same line
```
let x = 42;; let y= 43;;
```
(old behaviour is to evaluate the first phrase on the line), I find this change inconvenient.

This is with emacs 24.5.1, tuareg 2.1.0. I also have merlin 3.0.5 on both, but I doubt it is related as removing merlin in may virtual machine does not improve things.

**Comment by Chris00** [comment]
The problem is defining proper rules to choose between evaluating the phrase before and evaluating the phrase after `;;`.  Maybe if `;;` is the last thing on a line (possibly followed by some spaces only) and the point is after `;;` then evaluate the phrase before `;;`.

**Comment by ysalmon** [comment]
I think this is a good criterion.

Meanwhile I can roll back to tuareg 2.0.9, as 2.0.10 seems to be the release introducing the new behaviour. 

(the reason my main setup was showing the old behaviour is that I was in fact using an old tuareg version from elpa and not 2.1.0 from opam).

**Comment by Chris00** [comment]
Please pin the package if you would like to test the feature.

**Comment by erikmd** [comment]
Hi @Chris00, I believe that part of the issue mentioned by @ysalmon is still reproducible with tuareg master (I use GNU Emacs 25.1.1 on Debian stable):
if there is two phrases in the same line, like
```ocaml
let x = 42;; let y = 43;;
```
then only the last one is executed by <kbd>C-c C-e</kbd>, wherever is the point in this line...
Can you reproduce this?

**Comment by Chris00** [comment]
This is a different matter but I'll take a look at this.

**Comment by ysalmon** [comment]
Thanks a lot !

**Comment by erikmd** [comment]
Thank you @Chris00 ! :+1:
