### ISSUE TITLE
jbuild indentation is off

### ISSUE THREAD

**Issue by rgrinberg** [ocaml/tuareg#161]
See this snippet for example:

```
(alias
 ((name runtest)
  (deps ((files_recursively_in test-cases/ocaml-syntax)))
  (action
     (chdir test-cases/ocaml-syntax
  (setenv JBUILDER ${bin:jbuilder} (run ${exe:cram.exe} run.t))))))
```

That setenv should really be a little 1 space after the previous line.

**Comment by Chris00** [comment]
On my machine (Tuareg Git version — but no changes to jbuild since the last release) this is indented as
```elisp
(alias
 ((name runtest)
  (deps ((files_recursively_in test-cases/ocaml-syntax)))
  (action
   (chdir test-cases/ocaml-syntax
    (setenv JBUILDER ${bin:jbuilder} (run ${exe:cram.exe} run.t))))))
```
Do you run Emacs 25?

**Comment by rgrinberg** [comment]
Hmm, I run some nightly version of Emacs 26 actually. Looks like this is a problem with my environment.

**Comment by Chris00** [comment]
Or some changes/bug in SMIE?

**Comment by rgrinberg** [comment]
Perhaps my indentation settings are off. What are the relevant variables?

**Comment by Chris00** [comment]
>  What are the relevant variables?

None really — the jbuild mode is pretty much self-contained.  You may want to pin it and replace the SMIE line in the mode declaration with 
```
  (smie-setup tuareg-jbuild-smie-grammar #'verbose-tuareg-jbuild-smie-rules)
```
so you have an echo of what rule it invoked and what amount of indentation it requires.

**Comment by rgrinberg** [comment]
Hmm, I updated my version of tuareg and the problem no longer appears. Closing.
