### ISSUE TITLE
 Symbol's function definition is void: tuareg-list-definitions

### ISSUE THREAD

**Issue by vzaliva** [ocaml/tuareg#163]
I have Tuareg 2.1.0 installed via MELPA. Emacs version: GNU Emacs 24.5.1 under Ubuntu.

I am trying to scan definitions via the menu item and get the following error:

"command-execute: Symbol's function definition is void: tuareg-list-definitions"

I've tried to re-install tuareg package via MELPA but it did not help.

**Comment by Chris00** [comment]
Since `imenu` already does exactly this, I do not see the point in re-implementing this.  I will suppress the functionality and explain in the readme that imenu does this.
