### ISSUE TITLE
non-exhaustive pattern matching not detected

### ISSUE THREAD

**Issue by Ngalstyan4** [ocaml/tuareg#165]
The ocaml code below produces a compile time warning about non-exhaustive pattern match but tuareg-mode in emacs fails to recognize it.

```
let foo (a:int list) (f:int-> int list-> int): int =
  f 3 a

let _ = foo [1;2] (fun e (hd::tl) -> hd)

```

**Comment by rand00** [comment]
This gives a warning for me.
* GNU Emacs 25.3.50.1 (x86_64-pc-linux-gnu) of 2017-09-15
* Tuareg Version 2.1.0

**Comment by Chris00** [comment]
The toplevel in Emacs also shows the warning for me (Emacs 25.2.2, development version of Tuareg).  Could you say what versions you are using?

**Comment by Chris00** [comment]
I can't reproduce the error.  Compiling withing Emacs highlight the error.  Please reopen this issue with more information if the problem persists on your side.
