### ISSUE TITLE
Syntax highlighting for variant tags?

### ISSUE THREAD

**Issue by Ps-Pencil** [ocaml/tuareg#166]
The variant tags doesn't seem to have any special syntax highlighting. Here is a comparison of tuareg-mode and caml-mode.
![tuareg](https://user-images.githubusercontent.com/3211831/35301097-9a67bf5e-0082-11e8-93b4-665eb5ddbe15.png)

I read the README and couldn't find anything useful. Is it not implemented or just me missing something?

**Comment by Chris00** [comment]
As you see in the right hand side, all capitalized names are colored in the same way — there is no distinction between modules and constructors.  In Tuareg, there are two different faces.  Customize `tuareg-font-lock-constructor-face` to highlight the constructors.

**Comment by Ps-Pencil** [comment]
Hi Chris00, thank you for the explanation. Is there any possible values I can set? `describe-variable` gives no documentation and the value is the name of the variable itself.

**Comment by Chris00** [comment]
No, this is a face.  Use `face-spec-set` to set its characteristics.  For example:
```elisp
(face-spec-set 'modeline
	       '((((class color) (type tty)) (:inverse-video t))
		 (((class color) (background light))
		  (:foreground "Black" :background "Grey"))
		 (((class color) (background dark))
		  (:foreground "Black" :background "Grey"))))
```

**Comment by Chris00** [comment]
Example adapted to your specific question:
```elisp

    (face-spec-set
     'tuareg-font-lock-constructor-face
     '((((class color) (background light)) (:foreground "SaddleBrown"))
       (((class color) (background dark)) (:foreground "burlywood1"))
       (((class color) (type tty)) (:foreground "white"))))
```

**Comment by Ps-Pencil** [comment]
Thank you!
