### ISSUE TITLE
Invalid function: tuareg-with-internal-syntax

### ISSUE THREAD

**Issue by dsheets** [ocaml/tuareg#17]
With emacs 24.3, I get `Invalid function: tuareg-with-internal-syntax` in the minibuffer when indenting on both `master` and `2.0.8`. No functionality seems to be lost (but I haven't searched for brokenness very far).

**Comment by Chris00** [comment]
@letoh That should be fixed.  Please confirm that it works for you.

**Comment by Chris00** [comment]
@dsheets Please confirm too.
