### ISSUE TITLE
Phrase detection misled by comment after ;;

### ISSUE THREAD

**Issue by ysalmon** [ocaml/tuareg#170]
Hello,
this is a kind of a follow up on #158 : when a comment appears after ``;;`` (but on the same line), tuareg behaves in a strange way.

If the cursor lies strictly within the comment (that is on the ```*``` after the ```(```), hitting C-c C-e executes the comment itself ; if the cursor lies on any one of the two ```;```, it also executes the comment ; if the cursor lies strictly after ```;;``` and before the ```*``` of the comment (that is, up to and including the ```(```), hitting C-c C-e executes… the next phrase in the buffer (which leads to "Cannot send empty commands to OCaml REPL" if on the last phrase).

If the comment is on the line following ``;;`` instead, the behaviour is the same, except that having the cursor at the end of the line with ``;;`` executes the phrase before ``;;`` as intended in #158.

```ocaml
let x = 42;;

let y = 42;;   (* same-line*)

let s = 42;;
(* next-line *)

let z = x +  y;;
```

The behaviour when a comment is on the same line as the ``;;`` is confusing (at least to beginners) and I think that hitting C-c C-e from within the ``(* same-line *)`` comment above or any point on that line after the ``;;`` should execute the phrase ``let y = 42``. Of course this is a bit tricky as there might be a second phrase beginning on the same line after the comment…

For the ``(* next-line *)`` situation I am not so sure.

**Comment by Chris00** [comment]
I pushed a new way of determining which phrase to select to https://github.com/Chris00/tuareg
Could you please test it and report?

**Comment by Chris00** [comment]
@ysalmon I rewrote the `beginning-of-defun` function and used it for evaluation.  I considered that comments "sticking" to a definition (as in you snippet) are part of that definition.  So evaluating with the point anywhere on the line _next-line_ evaluates `s`.
