### ISSUE TITLE
What is tuareg-light?

### ISSUE THREAD

**Issue by rgrinberg** [ocaml/tuareg#173]
I see it included as part of the distribution but I'm not really sure what this mode is about (is it a rewrite of tuareg?). It would be nice to clarify its purpose.

**Comment by Chris00** [comment]
I'm not sure about its purpose either.  It was created in 2011 by Sean McLaughlin when he was at JSC and the commit message does not give any clue.  IMO, this file could be removed.

**Comment by rgrinberg** [comment]
I'm also for deleting it. If we ever want it back it's always in the git
history

**Comment by emaphis** [comment]
I wonder if it may have been a mode fore caml light?

**Comment by Chris00** [comment]
Not sure but Caml light is long dead anyway...
