### ISSUE TITLE
`tuareg-interactive-send-input` should take precedence over `comint-send-input`

### ISSUE THREAD

**Issue by rand00** [ocaml/tuareg#174]
I've found myself needing to define
``` elisp
(defun my-tuareg-interactive-settings ()
  (progn
    (define-key tuareg-interactive-mode-map (kbd "RET") 'tuareg-interactive-send-input)
    (define-key tuareg-interactive-mode-map (kbd "C-m") 'tuareg-interactive-send-input)
    (setq indent-line-function 'ocp-indent-line)
    )
  )
(add-hook 'tuareg-interactive-mode-hook 'my-tuareg-interactive-settings t)
```
.. to get a more proper REPL command-history. The 
``` elisp
...
    (define-key map [return] 'tuareg-interactive-send-input)
    (define-key map [(shift return)]
      'tuareg-interactive-send-input-end-of-phrase)
    (define-key map [(ctrl return)]
      'tuareg-interactive-send-input-end-of-phrase)
...
```
... part of `tuareg.el` doesn't work for me. 

I'm running ubuntu 16.04 using `emacs -nw`.

The `ocp-indent-line` is another but related issue, as when I switch over to `'tuareg-interactive-send-input` it calls `tuareg-interactive--indent-line` which doesn't indent properly for me. I.e. I get a next line after pressing "RET" with a lot of prefixing spaces. I can make another issue for that if you want.

\* edit: typo

**Comment by Chris00** [comment]
In which shell are you running Emacs?  In some of them _Shift-Return_ and _Ctrl-Return_ will not work.  However typing `;;` and then _Return_ should always work.  If it does not, please describe the behavior you see.  Also, please say what version of Tuareg you are using.

> which doesn't indent properly for me. 

Please provide and example explaining the actual and the desired behavior.

**Comment by rand00** [comment]
* GNU Emacs 25.3.50.1 (x86_64-pc-linux-gnu) of 2017-09-15
* Tuareg Version 2.1.0
* rxvt-unicode 9.21-1build1 
* gnu screen 4.3.1-2build1 

Desired behaviour (or something like it, which I get when I use ocp-indent in tuareg):
``` ocaml
# 
  let x = 
    1 + 
    2 + 
    3
    ;;
          val x : int = 6
# 
  let f x =
    let g y =
      let x = x * 2 in
      x * y 
    in
    g x 
;;
```
This is what I get when using `'tuareg-interactive-send-input` without `ocp-indent` when just continuously writing without pressing tab at any point (which might be unfair as ocp-indent is not perfect here either):
``` ocaml
# 
let f x = 
  let g y = 
    let x = x * 2 in
    x * y
          in
          g x 
            ;;
              val f : int -> int = <fun>
# 
let x = 
  1 +
    2 + 
    3
      ;;
          val x : int = 6
```
... and when marking block and pressing `TAB`:
``` ocaml
# 
        let f x =
          let g y =
            let x = x * 2 in
            x * y 
          in
          g x 
        ;;
# 
          let x = 
            1 +
              2 + 
              3
                ;;
                
          val x : int = 6
```
My `TAB` key is bound as pr. standard to `indent-for-tab-command`, which seems to indent much better in case of `indent-line-function` is `smie-indent-line`.

**Comment by rand00** [comment]
> However typing ;; and then Return should always work.

I don't have a problem with getting expressions evaluated - the problem is that the fallback instead of `tuareg-interactive-send-input` is `comint-send-input` (because `[return]` doesn't work for me but `(kbd "RET")` does. `comint-send-input` has a bad history-behaviour where each line of input is put separately in history.
.. when I then rebind `tuareg-interactive-send-input` to `(kbd "RET")`, then I get the weird indentation instead

**Comment by Chris00** [comment]
Ah, OK, that's clearer.  Does it also happens if you do not use gnu-screen?

**Comment by rand00** [comment]
`C-m` and `RET` are still bound to `comint-send-input` if not using screen. 
I also use `xmodmap` but I don't directly touch `RET` in my `~/.Xmodmap`:
```
clear Lock
clear Control
clear Mod1
clear Mod2
clear Mod3
clear Mod4
clear Mod5

keycode  25 = w W w W braceleft Lstroke lstroke
keycode  40 = d D d D braceright ETH eth

keycode  26 = e E e E parenleft cent EuroSign
keycode  41 = f F f F parenright ordfeminine dstroke

keycode  27 = r R r R bracketleft registered registered
keycode  42 = g G g G bracketright ENG eng

keycode  28 = t T t T slash THORN thorn

keycode 135 = Multi_key


keysym Control_L    = Caps_Lock
keysym Caps_Lock    = Control_L

keysym onehalf 	    = Escape
keysym Escape 	    = onehalf

!keysym Menu	    = Multi_key
!< using keycode instead (we don't have a key to bind 'Menu' to (for switching back/forth)

add shift       = Shift_L Shift_R 
add lock        = Caps_Lock 
add control     = Control_L Control_R Super_R 
add mod1        = Alt_L Meta_L 
add mod2        = Num_Lock
!add mod3 	= 
add mod4        = Super_L Hyper_L 
add mod5        = ISO_Level3_Shift Mode_switch 
```

**Comment by Chris00** [comment]
What shows <kbd>C-h k RETURN</kbd>?

**Comment by rand00** [comment]
```
RET runs the command comint-send-input (found in
tuareg-interactive-mode-map)...
```

**Comment by rand00** [comment]
RET vs return => emacs -nw vs emacs in GUI mode
http://ergoemacs.org/emacs/emacs_key_notation_return_vs_RET.html
.. I think tuareg should have a RET keybinding for `tuareg-interactive-send-input` in terminal mode too. I don't care about the `C-RET` and `S-RET` keybindings which one can't make in the terminal - I'm fine with just writing `;;`.

Then there is the other issue with indentation - should I make another github issue for this?

**Comment by Chris00** [comment]
I now use `RET` for the binding but I need to understand the problem with different indentation behavior before I release it.  We can track that here.

**Comment by Chris00** [comment]
> Then there is the other issue with indentation - should I make another github issue for this?

Yes please.
