### ISSUE TITLE
opam install tuareg

### ISSUE THREAD

**Issue by AbdallahS** [ocaml/tuareg#182]
When trying to `opam install tuareg` from an emacs terminal, the compilation fails with the following message. On the same system, `opam install tuareg` succeeds when run from a regular terminal. Trying `opam install some-other-packages` from inside an emacs terminal works in my limited experience.

    #=== ERROR while compiling tuareg.2.1.0 =======================================#
    # context     2.0.0 | linux/x86_64 | ocaml-base-compiler.4.07.0 | https://opam.ocaml.org/2.0#0a0111c0
    # path        ~/.opam/4.07.0/.opam-switch/build/tuareg.2.1.0
    # command     ~/.opam/opam-init/hooks/sandbox.sh build make elc
    # exit-code   2
    # env-file    ~/.opam/log/tuareg-10503-d8a4ae.env
    # output-file ~/.opam/log/tuareg-10503-d8a4ae.out
    ### output ###
    # 25.2.2 (term:0.96) --batch -L . --no-init-file -f batch-byte-compile tuareg.el
    # /bin/sh: 1: Syntax error: word unexpected (expecting ")")
    # Makefile:50: recipe for target 'tuareg.elc' failed
    # make: *** [tuareg.elc] Error 2

**Comment by Chris00** [comment]
On 27 July 2018 at 13:20 GMT, Abdallah wrote:
>
> # 25.2.2 (term:0.96) --batch -L . --no-init-file -f batch-byte-compile tuareg.el

Emacs is not properly found: “25.2.2 (term:0.96)” should be instead “emacs” or the path to your version.  Could you check the Makefile and determine how the variable “EMACS” is set?

**Comment by Chris00** [comment]
Feel free to reopen when you can provide more information.
