### ISSUE TITLE
Module wrongly typeset as constructor after #show and #show_module

### ISSUE THREAD

**Issue by ysalmon** [ocaml/tuareg#185]
Greetings,

I recently started using the new possibility to typeset constructors in a different color ; I think this is great for teaching.

It just occurred to me that tuareg detects module names as constructors in the following REPL constructs :
```
#show_module Stack;;
#show Stack;;
```
The parser in tuareg should be updated to take these into account. The ```#show``` directive can be applied to may things but not litteral constants including constructors, so there is no ambiguity.

**Comment by Chris00** [comment]
Thanks for reporting.

**Comment by ysalmon** [comment]
Thanks for the commit.

It corrected the problem in the OCaml REPL buffer but not in the source code buffer (where I agree it is a bit strange to have a ``#show`` but can still happen).

**Comment by Chris00** [comment]
Done.  Let me know what you think.

**Comment by ysalmon** [comment]
Works well. Thanks again !
