### ISSUE TITLE
Symbol prettification improperly applied to error message

### ISSUE THREAD

**Issue by ysalmon** [ocaml/tuareg#186]
With symbol prettification activated, tuareg replaces "not" with "¬ " in OCaml error message
```
Error: This expression has type bool array array
       but an expression was expected of type 'a option array array.
       Type bool is ¬ compatible with type 'a option. 
```
Note  : this is with Error font lock activated (error message is in red bold, no OCaml syntax coloration).

**Comment by Chris00** [comment]
You mean in interactive mode (REPL), right?

**Comment by Chris00** [comment]
Thanks for reporting.
