### ISSUE TITLE
tuareg-mode doesn't find .annot files in case they are not in _build/

### ISSUE THREAD

**Issue by UnixJunkie** [ocaml/tuareg#19]
Not all OCaml code is compiled with ocamlbuild.

For example, obuild (https://github.com/ocaml-obuild/obuild)
put build results inside of dist/ .

Apparently there is a fix proposed for some .el files here:
http://stackoverflow.com/questions/5004293/how-can-i-specify-a-custom-path-to-the-annotation-files-in-tuareg-mode-emacs

**Comment by Chris00** [comment]
See https://github.com/ocaml/ocaml/pull/139

**Comment by UnixJunkie** [comment]
Can tuareg mode handle the .cmt files instead of the .annot files?
I mean, the files which are generated when using the -bin-annot option of the compiler.

**Comment by UnixJunkie** [comment]
Thanks for the fix with the .annot files by the way.

**Comment by Chris00** [comment]
> Can tuareg mode handle the .cmt files instead of the .annot files?

Not at the moment.  Not a priority as [merlin](https://github.com/the-lambda-church/merlin) provides it.  On the other hand, maybe it is not that much work and it would be nice to have it to work out of the box.

**Comment by UnixJunkie** [comment]
Yeah, I start to use merlin in a minimal way (on top of tuareg-mode), I was just curious.
