### ISSUE TITLE
Consider # as punctuation rather than a symbol constituent

### ISSUE THREAD

**Issue by Wilfred** [ocaml/tuareg#191]
`self#foo` or `super#foo` is really a call to `foo`. If `#` is a symbol constituent, Emacs thinks that `self#foo` is the whole symbol, distinct from `foo`.

This means that tools like `highlight-symbol-mode` or `(symbol-at-point)` aren't as accurate.

The relevant line from tuareg.el is this:

```emacs-lisp
(modify-syntax-entry ?# "_" st)     ;Make name#method a single symbol
```

Would you be willing to change `#` to be considered as punctuation in the syntax table?

**Comment by Chris00** [comment]
Thanks for reporting this.  I have followed your suggestion.
