### ISSUE TITLE
Metaocaml support not indenting properly?

### ISSUE THREAD

**Issue by rneswold** [ocaml/tuareg#195]
I'm using OCaml 4.07.1+BER and have installed Tuareg 2.2.0 on my system. For standard OCaml programming, tuareg works great. But I've seen issues when using Metaocaml code. Although it highlights the quotes and escapes, the indentation seems broken. Even this simple file is indented incorrectly:

```
let f () = .< 0.0 >.

             let g () = true
```

My `.emacs` file has `(setq tuareg-support-metaocaml t)` in it. Is there some other setting I need to use?

**Comment by Chris00** [comment]
On 25 November 2018 at 17:08 CET, Rich Neswold wrote:
>
> let f () = .< 0.0 >.
>
>              let g () = true
>
> My .emacs file has (setq tuareg-support-metaocaml t) in it. Is there some other setting I need to use?

The new SMIE indentation engine indeed does not support MateOCaml (only syntax highlighting is supported at the moment).  I'll see what I can do but do not hold your breath.

**Comment by rneswold** [comment]
Much better! It even formats some of Oleg's more complicated examples correctly! Thanks!

(It does require spaces around the `.<` and `>.` brackets to properly recognize them, but I prefer that style of MetaOCaml formatting, so it's not an issue for me.)

**Comment by monnier** [comment]
Could you show some examples without spaces where it misbehaves?  I'll see if it can be fixed easily enough.

**Comment by rneswold** [comment]
```
let f x =
  let sum = ref 0.0 in
  for i = 0 to 10 do
    sum := .<.~x +. 10>.
done;
sum
```

If whitespace separates the `.<` and `.~` tokens, then the final two lines are correctly indented to the `for` loop. I think tuareg is treating `.<.~` as a single token when it searches for `>.`'s match.

**Comment by monnier** [comment]
>     sum := .<.~x +. 10>.

I just pushed a patch which should fix this case as well.

**Comment by rneswold** [comment]
Excellent! Thanks for fixing this! If I find any other weird combinations, I'll post them. But it's formatting everything I (and Oleg!) throw at it. :)
