### ISSUE TITLE
Highlighting builtin infix operators is quite slow

### ISSUE THREAD

**Issue by rgrinberg** [ocaml/tuareg#198]
Commenting out the following line yields a serious improvement in the highlighting performance for me:

```
     (,(concat
         "[][;,()|{}]\\|[-@^!:*=<>&/%+~?#]\\.?\\|\\.\\.\\.*\\|"
         (regexp-opt
          (if (tuareg-editing-ls3)
              '("asr" "asl" "lsr" "lsl" "or" "lor" "and" "land" "lxor"
                "not" "lnot" "mod" "fby" "pre" "last" "at")
            '("asr" "asl" "lsr" "lsl" "or" "lor" "land"
              "lxor" "not" "lnot" "mod"))
          'words))
      . tuareg-font-lock-operator-face)
```

**Comment by Chris00** [comment]
Did you use some tool to measure speed or is it noticeable visually?

**Comment by rgrinberg** [comment]
It is quite noticeable visually at first but I confirmed my findings with a font lock profiler

**Comment by Chris00** [comment]
@rgrinberg Is it OK on your side?

**Comment by rgrinberg** [comment]
Looks good to me. It's a bit problematic for me to test this, as it's only an issue on specific files. I will report after some thorough usage if the issue persists.

**Comment by Chris00** [comment]
> it's only an issue on specific files.

That's why I ask! ☺ I've tried to measure that it is faster but do not have a file on which I observed the slowness you mention.  If you do not report anything in the next days, I'll merge in the main repo.

**Comment by rgrinberg** [comment]
Yes, definitely feel free to merge :) These font lock issues are annoyingly hard to track down. For the record, whenever I encounter a file that Emacs is slowing down and I'm suspicious of the syntax highlighting, I do the following:

* Turn off font-lock-mode and see if the slowness persists
* If it does, I use https://github.com/Lindydancer/font-lock-profiler to identify the problem. The problem is usually easily found this way, as it's usually some wild regexp that is doing a lot of backtracking some edge cases.

**Comment by Chris00** [comment]
> I use https://github.com/Lindydancer/font-lock-profiler 

That's the one I've been using as well (from [MELPA](https://melpa.org/#/font-lock-profiler)).  It is good but I wish it would show absolute numbers in addition to percentages because it is not always easy to figure out whether some change have an appropriate global effect.
