### ISSUE TITLE
Is this the official repo now?

### ISSUE THREAD

**Issue by swsnr** [ocaml/tuareg#2]
I'm slightly confused at the state of Tuareg Mode.  

Is this project now the “official home” of Tuareg Mode?  Where should I report issues now, and from where should I install Tuareg Mode?

There's also a [project on OCaml Forge](https://forge.ocamlcore.org/projects/tuareg/), but it's repository is some commits behind this one.  However, issues seem to be handled, that is, there some recent issues and people comment on them.  On the other hand, this repo has just one issue (which a collaborator commented on, though).

**Comment by rneswold** [comment]
The README.md file still says "Bug reports & patches: use the tracker: https://forge.ocamlcore.org/tracker/?group_id=43." If you want issues reported through GitHub, this line should be changed or removed.

**Comment by Chris00** [comment]
Thanks for noticing!
