### ISSUE TITLE
Operator tokens no longer set in operator-face

### ISSUE THREAD

**Issue by jberdine** [ocaml/tuareg#204]
After https://github.com/Chris00/tuareg/commit/ed4decb8ffe87641cca5cb306d55bd35686775fd and https://github.com/Chris00/tuareg/commit/f330e11d67c77d85db955d3b11dd4408bceacf55 many tokens that are syntactically operators but are not user-defined infix operators are no longer set in operator-face.

For example with https://github.com/ocaml/tuareg/commit/8708c3397ea0f8ace3cfc24f15c2a1bc12534d65 I see
![image](https://user-images.githubusercontent.com/1466830/56092079-47e52c80-5eaf-11e9-8f11-3d3717ceea80.png)
while with https://github.com/Chris00/tuareg/commit/cd5229e0b7f43b5960e947555a5bfdb77f5528df I see
![image](https://user-images.githubusercontent.com/1466830/56092107-98f52080-5eaf-11e9-9293-59a26b572a4d.png)
Note that `;` and `=` are missing their highlighting.

**Comment by Chris00** [comment]
I have pushed commits to have better highlighting of function arguments.  It works on declarations such as
```ocaml
let f (A(x:t), B x, {z = s; p = Q e}) = body
```
@jberdine I'll be grateful if you could test and report!

**Comment by jberdine** [comment]
Thanks for working on this! I have tested this a bit and the highlighting of function arguments is improved. Other than function arguments, there are oddities and missing highlighting, however. See e.g.
<img width="345" alt="Screen Shot 2019-04-15 at 10 02 57 PM" src="https://user-images.githubusercontent.com/1466830/56165324-8faca680-5fca-11e9-9fd2-4fa9de6d35bd.png">
Note the missing highlighting of all but one of the fields in the type definition, and all of them in the record expression, as well as the other operator tokens like `;`, `:`, and `=` missing highlighting.

I admit to being confused by the change. It looks much more involved than I expected. Couldn't the regex for operators be relaxed to include all these cases at once, as was the case before? Alternatively, perhaps a face could be added for identifiers, which currently fall back to the default face, so that identifiers and operators can be given distinct faces?

**Comment by Chris00** [comment]
For
```ocaml
type t =
  { first: A.t; (* and *)
    second: B.t;
    third: C.t }
```
it is fixed — I encountered a similar problem.

**Comment by Chris00** [comment]
> Note the missing highlighting of all but one of the fields in the type definition, and all of them in the record expression, 

The names of record fields were not highlighted in the past — and neither in the current version.  I do not think they should.  (And it is kind of hard to detect them reliably in the presence of arbitrary expressions in between.)

**Comment by Chris00** [comment]
> operator tokens like ;, :, and = missing highlighting

These are *not* OCaml operators in phrases such as `let _ = {first = x; second = y; third = z}`.  I do not think they should receive any special treatment.

**Comment by Chris00** [comment]
> perhaps a face could be added for identifiers

What do you mean by “identifiers”?  Do you mean the [record fields](https://caml.inria.fr/pub/docs/manual-ocaml-4.07/values.html#sec94)?

**Comment by Chris00** [comment]
Note that the current highlighting is finer than the previous one.  In a phrase such as
```ocaml
let f (A(x:t), B x, {z = s; p = Q e}) = body
```
`z` and `p` are not highlighted, which was not possible with the previous approach.

**Comment by Chris00** [comment]
For the record, here is what the above snippet look like today:
![code preview](https://user-images.githubusercontent.com/1255665/56223984-1b780e80-606f-11e9-9948-5a16a2252341.png)
