### ISSUE TITLE
Update interface to ocamldebug

### ISSUE THREAD

**Issue by Chris00** [ocaml/tuareg#205]
The [format of code pointers changes](https://github.com/ocaml/ocaml/pull/8654): it used to be a number, but which is now written in the form `<id of code fragment>:<position in this code fragment>`.

**Comment by jhjourdan** [comment]
Gentle ping! OCamldebug 4.10 will stop working with emacs if this issue is not solved.

**Comment by Chris00** [comment]
Thanks for the reminder.  I started to work on it but have to complete it.  One thing that would help me is an example of each of the messages that are affected by this change — to make sure not to forget a case.

**Comment by jhjourdan** [comment]
Alright, looking at the code, the messages are:
- `Removing breakpoints...\n` (list of code pointers, one per line)
- `Setting breakpoints...\n` (list of code pointers, one per line)
- `Breakpoint 1 at <code ptr>: xxxx\n`
- `Removed breakpoint 1 at <code ptr>: xxxx\n`
- `Can\'t add breakpoint at pc %i:%i: no event there.`
- Answer to `info breakpoint`: an array of "Num    Address  Where" (Address == code ptr)
- Answer to `info events`: an array of "Address  Characters        Kind      Repr" (Address == code ptr)
- Prompt: `Time: %Li  - pc: <code ptr>`
- When a stack frame is displayed: `#<frame id>  Pc: <code ptr>  <module> char <character number>@.`

That should be all.

**Comment by jhjourdan** [comment]
@Chris00 : Do you think you could do that before the 4.10 release? This would be great if we could have emacs for testing this and fixing bugs in the beta...

**Comment by jhjourdan** [comment]
Up!

**Comment by Chris00** [comment]
@jhjourdan It seems that (o)camldebug are failing since some time because [running the tutorial program](https://ocaml.org/learn/tutorials/debug.html#The-OCaml-debugger) until OCaml 3.12 gave the output (content of `ocamldebug-filter-accumulator`)
```
"Time : 12 - pc : 14404 - module Uncaught
Breakpoint : 1
^Z^ZM./uncaught.ml:102:129:before
(ocd) "
```
while since OCaml 4, the output is
```
"done.
Time: 23
Program end.
Uncaught exception: Not_found
^Z^ZH
(ocd) "
```
This later output does not contain enough information to set `ocamldebug-last-frame` (in particular the filename) and so, say, `C-cC-b` on the ocamldebug buffer fails.

Since that problem has not been reported, I guess no one uses the commands in the ocamldebug buffer?

Also, since I barely use ocamldebug, may you write a list of instructions that used to work with the older OCaml version but fails with the current one?  That will allow me to test my changes — and maybe also to convert it to automatic tests.  Thanks.

**Comment by jhjourdan** [comment]
I am not, myself, a user of Ocamldebug under Emacs. There was simply a [demand](https://github.com/ocaml/ocaml/issues/6792#issuecomment-473043263) from @damiendoligez so that my change does not break it.

Hence, I am not able to answer your question: I don't know thelist of instructions that are supposed to work under Emacs modes.

That being said, perhaps some of its potnetial users may help you. @ppedrot, @maximedenes, @whitequark and @damiendoligez, could you help @Chris00 by telling him what is supposed to work in the ocamldebug support in Emacs modes ? Otherwise, if nobody complains about this not working, then I guess it is time to drop this support.

**Comment by ppedrot** [comment]
I am not an Emacs user, sorry. :shrug:
