### ISSUE TITLE
Syntax Highlighting Bottlenecks

### ISSUE THREAD

**Issue by rgrinberg** [ocaml/tuareg#208]
The latest improvements make tuareg a lot faster, and far less likely to slow down when fontifying large buffers. Thanks!

However, there are still some issues and jitter when editing medium sized buffers. In particular, `build_system.ml` in dune's source seems to be quite a bit slower than desired.

I've done a bit of profiling and I believe these three functions are quite time consuming:

* `tuareg--pattern-pre-form-let`
* `tuareg--pattern-pre-form-fun` this one isn't so bad in build_system.ml but can be quite bad in other buffers
* `tuareg--pattern-vars-matcher`

Here's some relevant data from the font lock profiler:

```
  53           294            34%  ("\\(?:\\<\\(?:\\(let\\(?:[-$&*+/<=>@^|][!$%&*+-./:<=>?@^|~]*\\)?\\)\\(\\(?:%\\<[A-Za-z_][A-Za-z0-9_']*\\>\\(?:\\.\\<[A-Za-z_][A-Za-z0-9_']*\\>\\)*\\)?\\(?:\\[@\\<[A-Za-z_][A-Za-z0-9_']*\\>\\(?:\\.\\<[A-Za-z_][A-Za-z0-9_']*\\>\\)*\\(?:[^][]\\|\\[\\(?:[^][]\\|\\[\\(?:[^][]\\|\\[[^][]*\\]\\)*\\]\\)*\\]\\)*\\]\\)*\\)\\(?: +\\(rec\\)\\)?\\|\\(and\\(?:[-$&*+/<=>@^|][!$%&*+-./:<=>?@^|~]*\\)?\\)\\) +\\|\\(\\_<class\\(?: +type\\)?\\(?: +virtual\\)?\\>\\) *\\(\\[ *'[A-Za-z_][A-Za-z0-9_']*\\> *\\(?:, *'[A-Za-z_][A-Za-z0-9_']*\\> *\\)*\\] *\\)?\\)" (tuareg--pattern-vars-matcher (tuareg--pattern-pre-form-let) nil (0 font-lock-variable-name-face keep)) (tuareg--pattern-maybe-type-matcher nil nil (1 font-lock-type-face keep)))
  54            66            14%  ("\\_<fun\\_>\\(?:%\\<[A-Za-z_][A-Za-z0-9_']*\\>\\(?:\\.\\<[A-Za-z_][A-Za-z0-9_']*\\>\\)*\\)?\\(?:\\[@\\<[A-Za-z_][A-Za-z0-9_']*\\>\\(?:\\.\\<[A-Za-z_][A-Za-z0-9_']*\\>\\)*\\(?:[^][]\\|\\[\\(?:[^][]\\|\\[\\(?:[^][]\\|\\[[^][]*\\]\\)*\\]\\)*\\]\\)*\\]\\)*" (tuareg--pattern-vars-matcher (tuareg--pattern-pre-form-fun) nil (0 font-lock-variable-name-face keep)))
```

Would it be possible to explain the purpose of these functions and how they contribute to syntax highlighting? It would be nice to know if it's possible to make some trade-offs here to make the highlighting less precise in favor of speed. It seems as if tuareg is doing quite a bit of work to "approximately" parse OCaml and this seems a bit too costly in real world use cases.

**Comment by quakerquickoats** [comment]
Oh, I see this thread now. These must be highlighting of "operators" - which is my favorite feature. Is there a way we can have this optional ? There is not a time I would encounter emacs buffers large enough to slow font locking without inspiring me to sanely and split up the file into more digestable portions. I would like to become more involved in this issue if possible.

**Comment by Chris00** [comment]
> explain the purpose of these functions

`tuareg--pattern-pre-form-let` detects the next `=` following a `let` to determine the region to highlight for function arguments.  It has a limit of 800 chars (this may be a bit much, maybe it could be lowered to, say, 256?).  `tuareg--pattern-pre-form-fun` does a similar job for `->` after a `fun`.  `tuareg--pattern-vars-matcher` is repeatedly called by font-lock to identify variables in the delimited region (the detection is much better than before).

Note that if you set `font-lock-maximum-decoration` to `0`, this is not performed.  (But I agree that if we can make the default more efficient, we should.)

P.S. This has nothing to do with highlighting operators.

**Comment by Chris00** [comment]
> In particular, build_system.ml in dune's source seems to be quite a bit slower than desired.

My machine is probably too fast because this happens instantly for me.  The profile I get is similar to yours.  `tuareg--pattern-pre-form-let` is the one taking most of the time.

**Comment by Chris00** [comment]
May you evaluate `(benchmark 10000 '(syntax-ppss))` with the point at the end of the buffer `build_system.ml` (using `M-:`) and report the results?  On my machine, I get 0.16–0.18 seconds.

**Comment by rgrinberg** [comment]
I got this: `"Elapsed time: 0.047416s"`

That's quite fast, but isn't this a cached value? When you are editing or moving around the buffer, you will not getting this many cache hits.

**Comment by Chris00** [comment]
On 16 May 2019 at 14:55 CEST, Rudi Grinberg <notifications@github.com> wrote:
>
> I got this: "Elapsed time: 0.047416s"
>
> That's quite fast, but isn't this a cached value? When you are editing or moving around the buffer, you will not getting this many cache hits.

This is correct.  This was to have a baseline.  I'll try to avoid syntax-ppss.  The two commits pushed should already make a (slight) difference.

**Comment by Chris00** [comment]
May you try the last commit (in [my repo](https://github.com/Chris00/tuareg))?

**Comment by rgrinberg** [comment]
I will try your commit tomorrow. Thanks @Chris00.

Btw, here's another profile damning the regex in question:

```
  53           901            99%  ("\\(?:\\<\\(?:\\(let\\(?:[-$&*+/<=>@^|][!$%&*+-./:<=>?@^|~]*\\)?\\)\\(\\(?:%\\<[A-Za-z_][A-Za-z0-9_']*\\>\\(?:\\.\\<[A-Za-z_][A-Za-z0-9_']*\\>\\)*\\)?\\(?:\\[@\\<[A-Za-z_][A-Za-z0-9_']*\\>\\(?:\\.\\<[A-Za-z_][A-Za-z0-9_']*\\>\\)*\\(?:[^][]\\|\\[\\(?:[^][]\\|\\[\\(?:[^][]\\|\\[[^][]*\\]\\)*\\]\\)*\\]\\)*\\]\\)*\\)\\(?: +\\(rec\\)\\)?\\|\\(and\\(?:[-$&*+/<=>@^|][!$%&*+-./:<=>?@^|~]*\\)?\\)\\) +\\|\\(\\_<class\\(?: +type\\)?\\(?: +virtual\\)?\\>\\) *\\(\\[ *'[A-Za-z_][A-Za-z0-9_']*\\> *\\(?:, *'[A-Za-z_][A-Za-z0-9_']*\\> *\\)*\\] *\\)?\\)" (tuareg--pattern-vars-matcher (tuareg--pattern-pre-form-let) nil (0 font-lock-variable-name-face keep)) (tuareg--pattern-maybe-type-matcher nil nil (1 font-lock-type-face keep)))
```

This one is from ocaml's `typecore.ml`. This is basically the entirety of the font lock phase. So really this is the only thing that needs some optimizing.

**Comment by Chris00** [comment]
With the changes, that rule looks like:
```
  54           901            11%  ("\\(?:\\_<\\(?:\\(let\\(?:[-$&*+/<=>@^|][!$%&*+-./:<=>?@^|~]*\\)?\\)\\(\\(?:%\\<[A-Za-z_][A-Za-z0-9_']*\\>\\(?:\\.\\<[A-Za-z_][A-Za-z0-9_']*\\>\\)*\\)?\\(?:\\[@\\<[A-Za-z_][A-Za-z0-9_']*\\>\\(?:\\.\\<[A-Za-z_][A-Za-z0-9_']*\\>\\)*\\(?:[^][]\\|\\[\\(?:[^][]\\|\\[\\(?:[^][]\\|\\[[^][]*\\]\\)*\\]\\)*\\]\\)*\\]\\)*\\)\\(?: +\\(rec\\)\\)?\\|\\(and\\(?:[-$&*+/<=>@^|][!$%&*+-./:<=>?@^|~]*\\)?\\)\\) +\\|\\(\\_<class\\(?: +type\\)?\\(?: +virtual\\)?\\>\\) *\\(\\[ *'[A-Za-z_][A-Za-z0-9_']*\\> *\\(?:, *'[A-Za-z_][A-Za-z0-9_']*\\> *\\)*\\] *\\)?\\)" (tuareg--pattern-vars-matcher (tuareg--pattern-pre-form-let) nil (0 font-lock-variable-name-face keep)) (tuareg--pattern-maybe-type-matcher nil nil (1 font-lock-type-face keep)))
```

**Comment by rgrinberg** [comment]
Your commits look quite good to me. I don't see any degradation in highlighting and a definite improvement in perf. Thanks a lot 💯
