### ISSUE TITLE
Broken highlighting when argument name starts with 'as'

### ISSUE THREAD

**Issue by cpitclaudel** [ocaml/tuareg#214]
In the following example, `typecheck` is highlighted with `variable-name-face` instead of `function-name-face`, seemingly because `ast` starts with `as`:

```ocaml
let typecheck ast =
  …
```

On the other hand, the following is correctly highlighted:

```ocaml
let typecheck expr =
  …
```

**Comment by Chris00** [comment]
Thanks.
