### ISSUE TITLE
let without explicit arguments face

### ISSUE THREAD

**Issue by Pitometsu** [ocaml/tuareg#215]
```ocaml
let example = ()
and example _ = ()
```
![Screenshot from 2019-08-15 19-01-52](https://user-images.githubusercontent.com/2434691/63108339-4461cf00-bf8f-11e9-9b63-19770ebc4623.png)

**Comment by Pitometsu** [comment]
Is it expected behaviour?

**Comment by Chris00** [comment]
The first is a variable, the second is a function.  Hence the different coloring.

**Comment by Pitometsu** [comment]
It's confusing, e.g. such refactoring:
```ocaml
let printer_1 s = Printf.printf "%s" s;;
let printer_2 = Printf.printf "%s";;
```
That still have same value, but different highlighting.

**Comment by Chris00** [comment]
```ocaml
let f x = g a x
let f = g a
```
may not have the same effect: the evaluation `g a` at the second line may have a side effect.

**Comment by Pitometsu** [comment]
:thinking: reasonable. Wellp, thanks for clarification.

**Comment by Pitometsu** [comment]
@Chris00 BTW could you be so kind to show such example, it would be interesting to see.

What I see is:
```ocaml
utop # let g a x = Printf.printf "%s" a; x;;
val g : string -> 'a -> 'a = <fun>
-( 19:53:34 )-< command 5 >----------------------------------------------------------------------{ counter: 0 }-
utop # let f x = g "hello" x;;
val f : 'a -> 'a = <fun>
-( 20:22:27 )-< command 6 >----------------------------------------------------------------------{ counter: 0 }-
utop # let f = g "hello";;
val f : '_a -> '_a = <fun>
```
Not so big difference (the first one still can  be universal, aka forall, and the second one can't be, if I understand it correctly).

**Comment by Chris00** [comment]
And what about
```ocaml
let g a = Printf.printf "%s" a; fun x -> x
```
