### ISSUE TITLE
Bad syntax highlighting of match statements

### ISSUE THREAD

**Issue by Wilfred** [ocaml/tuareg#217]
```
let get_fun fun_name =
  Memory_bounded_lru_cache.find_or_add
    decl_cache
    ~key:(Provider_config.Fun_decl fun_name)
    ~default:(fun () ->
      let result : fun_decl option =
        match Naming_table.Funs.get_pos fun_name with
        | None -> None
      in
      Obj.repr result)
```

Produces the following:

![Screenshot 2019-08-27 at 17 10 59](https://user-images.githubusercontent.com/70800/63788594-a99db480-c8ed-11e9-9b9e-bf2094902329.png)

The whole match clause is considered to be a type and is highlighted as such. I'm not sure why.

**Comment by Chris00** [comment]
Thanks for reporting!
