### ISSUE TITLE
tuareg-discover-phrase buggy or bad comment

### ISSUE THREAD

**Issue by bluewww** [ocaml/tuareg#218]
`tuareg-discover-phrase` claims to return  a triplet
> Return a triplet (BEGIN END END-WITH-COMMENTS) [...]

but infact it returns `(cons begin end)`.
This breaks `utop-eval-phrase`. I would suggest you either rectify the documentation or add the missing return value.

**Comment by rduplain** [comment]
e5e883c7926326ea748ab71fb07cb882c2908efe changed the return value of `tuareg-discover-phrase`.

**Comment by Chris00** [comment]
I fixed the documentation.  Hope it is not a problem for utop.  If it is, le me know and I'll rename the function and restore the old behavior.

**Comment by rduplain** [comment]
f8610c7df244bfded8935456bc42245526b13012 does improve the documentation to match the behavior.

For utop, a fix is still needed. A standard `opam user-setup install` installs utop.el here:

```
~/.opam/default/share/emacs/site-lisp/utop.el
```

... and this expects a triple: [source](https://github.com/ocaml-community/utop/blob/83ee76fc39b6cb394f5fb19063a3a7da09224339/src/top/utop.el#L217).

A crude patch in Emacs init can address this, to provide a compatibility fix which in effect aliases `end-with-comments` to the same value of `end`, which is suitable for utop interaction:

```emacs
(fset 'tuareg-discover-phrase-original
      (symbol-function 'tuareg-discover-phrase))

(fset 'tuareg-discover-phrase
      '(lambda ()
         "Fix `tuareg-discover-phrase' to return triple as expected."
         ;; Called by `utop-eval-phrase'.
         (let ((phrase (tuareg-discover-phrase-original)))
           (if (not (numberp (cdr phrase)))
               phrase
             (list (car phrase) (cdr phrase) (cdr phrase))))))
```

Does tuareg benefit from supporting a triple? If not ... speaking as a user, not a maintainer, utop is the natural project to maintain this compatibility, as it already has such logic [here](https://github.com/ocaml-community/utop/blob/83ee76fc39b6cb394f5fb19063a3a7da09224339/src/top/utop.el#L287). The discover-phrase call in utop.el could detect whether it has a double or triple, as in my patch above.

But, there are existing `opam` installations which have the utop.el which expects a triple. The workaround is to patch `tuareg-discover-phrase` or `utop-compat-discover-phrase` in Emacs Lisp to use existing utop and tuareg versions.

**Comment by Chris00** [comment]
I have [restored a definition of `tuareg-discover-phrase`](https://github.com/ocaml/tuareg/commit/9281ae54ac4c788dc2d915db63ec36b1d2273884) compatible with the original one.  May you please test that it works well with utop?  Thanks.

**Comment by rduplain** [comment]
Confirming that `tuareg-discover-phrase` works with utop without additional modification, on its expectation of a triple. Thanks!
