### ISSUE TITLE
tuareg-indent-phrase inside unclosed comment

### ISSUE THREAD

**Issue by tomjridge** [ocaml/tuareg#22]
The following .ml file:

```
(* this is an unclosed comment
```

Using tuareg, if you position the cursor inside the comment, and call ESC-q (tuareg-indent-phrase), the emacs process uses 100% CPU and becomes unresponsive, and then has to be killed and restarted.

This is clearly a bug. Can someone confirm this behaviour?

**Comment by Chris00** [comment]
I can reproduce the bug with Emacs  24.4.1 but I can interrupt.
