### ISSUE TITLE
Buffer eval malfunction in tuareg-mode

### ISSUE THREAD

**Issue by eazar001** [ocaml/tuareg#226]
Hi, I'm having an issue that I don't quite understand in Tuareg version 2.2.0. I made the following test code in my emacs editor:
```
open Core

let sumList list = List.fold_left (fun x y -> x + y) 0 list

let rec sumList'' acc (xs: int list) =
  match xs with
  | [] -> acc
  | x::xs -> sumList'' (acc + x) xs

let sumList' xs = sumList'' 0 xs
```

When I eval the buffer with (C-c C-b) I get this confusing message:

> Line 3, characters 34-52:
3 | let sumList list = List.fold_left (fun x y -> x + y) 0 list
                                      ^^^^^^^^^^^^^^^^^^
Error: This expression should not be a function, the expected type is 'a list

That is obviously wrong. My usage of `List.fold_left` is absolutely correct. As a matter of fact, this code works when I evaluate each individual expression manually! (C-x C-e)

Is this a bug? Am I missing something?

**Comment by Chris00** [comment]
> My usage of List.fold_left is absolutely correct.

It is not:
```ocaml
List.fold_left;;
- : 'a Core.List.t -> init:'b -> f:('b -> 'a -> 'b) -> 'b = <fun>
```
When you evaluate each expression manually, you probably forget to `open Core` which changes the meaning of `List.fold_left`.

**Comment by eazar001** [comment]
I still don't get the right answer by switching the arguments around:

```# sumList [1];;
- : init:((int -> int -> int) -> int -> '_weak1) ->
    f:(((int -> int -> int) -> int -> '_weak1) ->
       int -> (int -> int -> int) -> int -> '_weak1) ->
    '_weak1
= <fun>```

**Comment by eazar001** [comment]
Never mind. It works now, thanks. I just was not familiar with Ocaml's feature of labelled arguments.
