### ISSUE TITLE
Adding a dependency on ocp-indent

### ISSUE THREAD

**Issue by brokenpylons** [ocaml/tuareg#229]
Hi,

since the indentation seems to be broken in many cases and ocp-indent does it perfectly as far as I can tell, why not just add it as a dependency? I really don't see how using operator precedence parsing is ever going to produce satisfactory results for OCaml. I guess the other good option would be to make a recursive descent parser like they did in js2-mode (and make it incremental at least at the expression level), but that would be a lot of work...

**Comment by Chris00** [comment]
> be broken in many cases

That's not a very useful claim to make (and not one that I find true).  Opening specific issues would bu more useful.

> ocp-indent does it perfectly as far as I can tell, why not just add it as a dependency?

There is already `ocaml-indent` which provides an Emacs interface.  Tuareg should provide an self-contained indentation engine; that does not preclude using external ones.
