### ISSUE TITLE
Small font question

### ISSUE THREAD

**Issue by ttamttam** [ocaml/tuareg#235]
How do you make 

```lisp
(add-hook 'tuareg-mode-hook #'(lambda() (setq mode-name "🐫")))
```

really display a camel? I mean, is there a particular font I should use to have the camel instead of a "glyph not found replacement character"?

Best regards

**Comment by Chris00** [comment]
> How do you make
>
> (add-hook 'tuareg-mode-hook #'(lambda() (setq mode-name "🐫")))
>
> really display a camel? I mean, is there a particular font I should
> use to have the camel instead of a "glyph not found replacement
> character"?

On my machine, the camel comes from the package ttf-unifont.

**Comment by ttamttam** [comment]
OK. Installing a "fallback" font, like "symbola" solved it.

Sorry for the noise.
