### ISSUE TITLE
New string syntax

### ISSUE THREAD

**Issue by sheijk** [ocaml/tuareg#24]
OCaml 4.02 supports a new syntax for string literals like this `{eof|this is a string|eof}` which are great for multi line strings, etc. As far as I've seen they are not getting highlighted by Tuareg, yet (checked behavior of release 2.0.8 and quickly skimmed the git repo).

See [list of 4.02 changes](http://caml.inria.fr/pub/distrib/ocaml-4.02/notes/Changes), [documentation](http://caml.inria.fr/pub/docs/manual-ocaml/extn.html#sec244)

**Comment by Chris00** [comment]
For the alignment issue, go to #5
