### ISSUE TITLE
Automatic indentation?

### ISSUE THREAD

**Issue by progman1** [ocaml/tuareg#245]
hi

the emacs mode info on tuareg says:
Dedicated to Emacs and XEmacs, version 21 and higher.  Provides
automatic indentation and compilation interface

If I use a combination of ```<C-j> and <tab> ``` I get
local indentation but I am not sure whether you mean this for
the 'automatic' mentioned above.

there is also
tuareg-comment-dwim
tuareg-indent-phrase
and the insert commands

If you mean something other than these commands, 
can you say something more about it?
thanks.

**Comment by Chris00** [comment]
Well, I'm not sure what you mean exactly by _local indentation_.  It's automatic in the sense that, say, if you write `let f x =` and then press <kbd>enter</kbd>, it puts you at the right place on the next line.  You can also automatically re-indent a block by pressing <kbd>M-q</kbd>.
