### ISSUE TITLE
'tuareg-eval-phrase' and the 'if-then-else' expression

### ISSUE THREAD

**Issue by Fourchaux** [ocaml/tuareg#256]
(* tuareg 20210628.1257 - OCaml 4.12.0 - Emacs 28.0.50 *)
The 'tuareg-eval-phrase' saga continues with:
```ocaml
if true then 1 else 2 ;; (* Syntax error + cursor moving to the beginning of 'then' *)
(*
Line 1, characters 7-9:
1 | if true;;
           ^^
Error: Syntax error
*)

(* Note: the following is OK *) 
(if true then 1 else 2) ;;
(* - : int = 1 *)
```

**Comment by mattiase** [comment]
Thank you! Looks like it's time for some service-après-vente again.
Does this pull request help?

**Comment by Fourchaux** [comment]
Yep. Le SAV est OK.  :+1:

**Comment by mattiase** [comment]
Thanks for testing, and the ghost of the machine has been kind to merge it. Close if you are happy!
