### ISSUE TITLE
Time for a new release in opam?

### ISSUE THREAD

**Issue by pmetzger** [ocaml/tuareg#260]
The version of this code in MELPA is much newer than the version in opam. Might it be time to do a new opam release?

**Comment by monnier** [comment]
Perry E. Metzger [2021-07-27 14:29:13] wrote:
> The version of this code in MELPA is much newer than the version in
> opam.  Might it be time to do a new opam release?

Don't know about opam, but it's probably time for a new release, indeed.


        Stefan

**Comment by mattiase** [comment]
Would be nice to have CI working again.

**Comment by Chris00** [comment]
I'll try to make a new release in OPAM soon — I need to sync it with a release of `caml-mode` as well.

**Comment by Chris00** [comment]
@mattiase Yes, we should use Github actions for that.  Feel free to submit a PR.

**Comment by mattiase** [comment]
PR #264 has now been created for that purpose.

**Comment by bcc32** [comment]
Tangentially related, I see a non-GNU ELPA release named 2.3.0, but no corresponding tag on GitHub.

**Comment by Chris00** [comment]
My mistake: I bumped the version and NonGNU ELPA took it as a new version.

**Comment by Chris00** [comment]
There are still a several PR to take care of before making a release.

**Comment by monnier** [comment]
Christophe Troestler [2021-09-14 14:26:06] wrote:
> My mistake: I bumped the version and NonGNU ELPA took it as a new version.

If you want to bump the `Version:` without making a release (yet), then
you can make it something like `Version: 2.4-dev` (other than `-dev` you
can use `-git` or `-snapshot` or `beta` or `alpha` or `pre`).

**Comment by ysalmon** [comment]
Hi,
chiming in to enquire about the possibility of a new opam release.
I understand some thing may still be unfinished in eg. caml-mode, but there are interesting bugfixes in the git repo (regarding phrase evaluation, notably) that might be cause for a 2.2.1 if not a 2.3.0.

**Comment by bbatsov** [comment]
That also seems related to #283. I myself am a bit puzzled which is the current version - most like 2.3.0.

**Comment by bbatsov** [comment]
> I'll try to make a new release in OPAM soon — I need to sync it with a release of caml-mode as well.

Btw, what's the exact dependency of `tuareg` to `caml-mode`? I've noticed there was just an optional dependency on `caml-types` and I guess that becomes redundant if someone is using `merlin` or OCaml LSP. Is the relationship between tuareg and caml-mode documented somewhere?

**Comment by Chris00** [comment]
> Anything in particular blocking this?

Just my lack of time.  I've done a [new release](https://github.com/ocaml/opam-repository/pull/22173) but for the next ones some help will definitely be needed.

**Comment by pmetzger** [comment]
You might want to ask about it on the ocaml discuss?

**Comment by bbatsov** [comment]
> Just my lack of time. I've done a https://github.com/ocaml/opam-repository/pull/22173 but for the next ones some help will definitely be needed.

If you need more Tuareg contributors you can sign me up. I think it's well known that I have a weakness for maintaining Elisp modes. :-) Perhaps I'll find the time and the desire to carry out this merge with caml-mode we've discussed recently.
