### ISSUE TITLE
Extremely slow font-lock

### ISSUE THREAD

**Issue by lpw25** [ocaml/tuareg#27]
I've been having a few cases where tuareg freezes for a long time since I upgraded to emacs 24.3.1 and a recent tuareg mode (currently 20141026.743 from one of the ELPAs).

A simple reproduction case (tested with `emacs -Q`) is:

```ocaml
class bar = (foo object method private foo : int end
```

If I place the cursor on the `o` in `object` and type `:` it takes about 30 seconds to respond. If I then press space it freezes entirely (possibly an infinite loop but probably just such a long time that I give up and kill emacs).

If I run the profiler on the 30 second example, it says that 90+% of the time was in some jit-lock functions, so I assume that's where the problem is.

**Comment by lpw25** [comment]
>  but there are always more urgent things to do...

Outside of maintaining tuareg mode I'm sure there are many more urgent things, but I don't think there is anything more urgent in terms of tuareg mode: at this point it is forcing me to turn off font-lock on quite a few of my large OCaml files.

**Comment by Chris00** [comment]
I cannot reproduce the behavior with version 24.4.1 of Emacs and the HEAD of Tuareg.  @lpw25 What versions are you using?

**Comment by lpw25** [comment]
I am currently using version 24.4.1 Emacs and 20141026.743 of Tuareg from MELPA. I also observed it with Emacs 24.3.1 and the same version of Tuareg.

**Comment by antegallya** [comment]
Hello, I bisected the bug to be introduced by commit c93a698b6ed6eb9b773ae714e65dfed9140edc51 on my system.

**Comment by Chris00** [comment]
On Mon, 19 Jan 2015 05:27:14 -0800, Pierre Hauweele wrote:
> 
> Hello, I bisected the bug to be introduced by commit c93a698 on my system.

Could you please try the branch "highlighting"?  Thanks.

**Comment by antegallya** [comment]
Fixed for me in the "highlighting" branch ;-)
Thanks.

**Comment by lpw25** [comment]
The latest version in MELPA (20150130.1537) -- which includes the changes from the highlighting branch seems to fix the issue for me. Thanks!
