### ISSUE TITLE
Package cl is deprecated

### ISSUE THREAD

**Issue by fengdlm** [ocaml/tuareg#284]
Hi,

Is there any plan to remove the dependency on `cl-lib`? Every time I start emacs, I see this message `Package cl is deprecated`, I assume eventually emacs will retire `cl-lib`.

**Comment by mattiase** [comment]
> I assume eventually emacs will retire cl-lib

There is no such plan. The reason for deprecating the `cl` package is that it takes liberties with the elisp namespace and (in particular) redefines some standard functions and macros. `cl-lib` uses the `cl-` prefix for all its definitions.

**Comment by fengdlm** [comment]
Thanks for the explanation.
