### ISSUE TITLE
Tuareg depends on emacs-nox

### ISSUE THREAD

**Issue by craff** [ocaml/tuareg#285]
It forces me (on debian-stable) to deinstall debian-gtk.

tuareg shoud depend on emacs-common only ?
or emacs-nox | emacs-gtk | emacs-lucid ?

**Comment by craff** [comment]
This is probably an issue with conf-emacs ... but I do not know where conf-emacs git or alike is.

**Comment by bbatsov** [comment]
Isn't this specific to the Debian package? Probably it should be raised with the package maintainer there.

**Comment by craff** [comment]
No this is a problem of conf-emacs... and has disappeared since I upgraded to tuareg 2.2.0.
I close the issue.
