### ISSUE TITLE
Triggers warning for using obsolete aliases on Emacs

### ISSUE THREAD

**Issue by eckertliam** [ocaml/tuareg#287]
Emacs >=27.1 gives the following warnings 

'ecase' is obsolete use 'cl-ecase' instead
'case' is obsolete use 'cl-case' instead
'assert' is obsolete use 'cl-assert' instead
'decf' is obsolete use 'cl-decf' instead

**Comment by monnier** [comment]
When/where?

I don't think these are due to Tuareg, since there is (for example) no occurrence of `ecase` in Tuareg's files.

**Comment by monnier** [comment]
> I am running Tuareg 2.2.0 on an M1 Mac with Emacs 28.1. I downloaded Tuareg from Opam.

Hmmm.. the latest version (2.3.0) dates back to Nov 2020, so 2.2.0 sounds quite old.
See http://elpa.nongnu.org/nongnu/tuareg.html
You may want to contact the maintainer of the Opam packaging of Tuareg
(not sure who that would be) to see how/if that can be updated.

We're actually overdue for a new version, but 2.3.0 should already solve
those problems (tho these are only warnings and should be harmless).


        Stefan

**Comment by eckertliam** [comment]
I will contact the package maintainer if possible. I appreciate your help.
