### ISSUE TITLE
Struct indentation

### ISSUE THREAD

**Issue by swsnr** [ocaml/tuareg#3]
Tuareg indents module definitions as follows currently:

``` ocaml
module Foo =
  struct
  end
```

Notice that the `struct` is indented relative to `module`.

How can I get Tuareg to _not_ indent `struct` relative to `module`, i.e.

``` ocaml
module Foo =
struct
end
```

**Comment by Chris00** [comment]
The indentation of `sig` now is
```ocaml
module type Self = sig
  include Printable.S
end
```
