### ISSUE TITLE
tuareg.3.0.0 fails to load in emacs on macOS when installed using opam

### ISSUE THREAD

**Issue by prachigauriar** [ocaml/tuareg#300]
I’m an OCaml newbie, so please forgive me if I did something wrong.

## Summary

I just tried a fresh install of OCaml and related tools on macOS. I’m using the directions from [Real World OCaml](https://dev.realworldocaml.org/install.html).  When installing tuareg.3.0.0 via opam, I can’t get tuareg-mode to work in emacs. Everything works fine with tuareg.2.2.0.

## Steps to reproduce

1. Install emacs via homebrew (`brew install --cask emacs`).
2. Install opam, etc.
    ```
    brew install opam
    opam install core core_bench utop
    opam install user-setup tuareg ocamlformat merlin
    opam user-setup install
    ```
4. Try to open an existing OCaml file (`emacs test.ml`)

## Expected Results

The file will open and tuareg-mode will be enabled (code will be syntax highlighted, etc.)

## Actual Results

The following message is displayed in emacs:

```
File mode specification error: (file-missing Cannot open load file No such file or directory tuareg-compat)
```

## System Details

MacBook Pro with Apple M1 Max
macOS 12.6
emacs 28.2
merlin 4.6-414
ocaml 4.14.0
ocamlformat 0.23.0
opam 2.1.3
tuareg 3.0.0
user-setup 0.7

## Additional Notes

Again, if I install tuareg.2.2.0, everything works as expected.

**Comment by Chris00** [comment]
This is fixed in [version 3.0.1](https://github.com/ocaml/opam-repository/pull/22185).
