### ISSUE TITLE
100% CPU hang on simple edit

### ISSUE THREAD

**Issue by choeger** [ocaml/tuareg#31]
In the source file [1]: hen I go to line 44 and insert the following code (just typing it), emacs hangs, just after typing '>':

```
let write_label o = function
    Path name ->
```

A trace is also attached ([2])

[1] https://raw.githubusercontent.com/choeger/modelica.ml/5d13b58f79a998f30a3186de30703f3a1a1fa21b/test/parse_package.ml
[2] http://pastebin.com/Dv8kbqBK

**Comment by Chris00** [comment]
Are you using the HEAD?

**Comment by choeger** [comment]
I am using tuareg from opam, which is packaged as 2.08 but still has 2.06 in tuareg-about (which is a small inconsistency in the 2.08 release)

Are there any recent changes that might have affected this issue? Is it difficult to try HEAD?

**Comment by Chris00** [comment]
> Are there any recent changes that might have affected this issue? 

Yes, the syntax highlighting code was completely rewritten.

> Is it difficult to try HEAD? 

No.  Just clone the repository in the directory of your choice, say `~/code/`, and add to your `~/.emacs` (or `~/.emacs.d/init.el`):
```
(add-to-list 'load-path "~/code/tuareg/")
```
I intent to release a new version of Tuareg soon but I'd like to close a few more annoyances first.
