### ISSUE TITLE
Pre-compiling on OSX may break

### ISSUE THREAD

**Issue by AltGr** [ocaml/tuareg#32]
See discussion at: http://lists.ocaml.org/pipermail/teaching/2015-January/000062.html

The issue is that OSX comes with an older, console version of Emacs, which will be used for the compilation at tuareg installation time; whilst most users will then be using a newer, graphic version, bundled as an app. The .elc that are generated with the older version generate strange problems (uncolored buffer, that can be colored by `font-lock-fontify-buffer` but then prints an error at every insert).

The easiest would be to not run the compilation by default in the OPAM package.

**Comment by AltGr** [comment]
For info: this has been verified with versions 22.1.1 and 24.4.1 (console and "app")

**Comment by Chris00** [comment]
Is there a way to reliably detect that the "Emacs app" is present?  What is the OPAM flag to use so compilation takes place except on OSX?

**Comment by monnier** [comment]
> The easiest would be to not run the compilation by default in the
> OPAM package.

Also, installation via M-x list-packages RET would eliminate
the problem.


        Stefan

**Comment by Chris00** [comment]
> installation via `M-x list-packages RET` would eliminate the problem. 

Absolutely but they want to automate the whole installation (Tuareg being only one component).

There is already an attempt at [detecting the app version](https://github.com/ocaml/tuareg/blob/master/Makefile#L20) on OSX.  Could you please tell me how to refine it? — I do not have a mac.

**Comment by AltGr** [comment]
Indeed, that works (it is'nt yet in the OPAM package, but I had success with pinning this git); although I am not sure it is possible to use the compiled code and remain portable in the general case. In the case above, the newer version works for Emacs.app but breaks the text-mode emacs (although with a cleaner error: "file xxx was compiled for Emacs version 23 or later"). And on OSX, there may also be an Aquamacs in the mix...

Even in the general case, it's possible that the system Emacs is changed, and that may break an already compiled Tuareg. On binary distributions, this is handled with hooks that'll register all .elc and make sure they are up-to-date whenever Emacs changes, but we don't have a mechanism to track system dependencies (yet -- there a are plans for this, see https://github.com/ocaml/opam/blob/master/doc/design/depexts-plugins)

So I am afraid that the only way to guarantee it won't break, at the moment, is to install no compiled files from the OPAM package ; the `post-message` may provide a hint on compiling, or installing through `M-x list-packages`...

**Comment by Chris00** [comment]
The [upcoming opam file](https://github.com/ocaml/tuareg/commit/ba2141ac68384f403ba29b586e2b0d5d8465b1a6) only installs `.el` files — as you did for [earlier versions](https://github.com/ocaml/opam-repository/pull/3507).
