### ISSUE TITLE
Tuareg hangs emacs after inputing `for i = `

### ISSUE THREAD

**Issue by duanchenggang** [ocaml/tuareg#36]
The problem could be reproduced by:

1. Open a new file in Tuareg mode.
2. Input `for i =` at the start of the file.
3. Input a space after `for i =` by pressing the space key.

Then emacs hangs.

The emacs version is `24.4.1`; caml package version is `3.12.0.1`; tuareg version is `2.0.8`.

**Comment by Chris00** [comment]
You are not using the HEAD right?

**Comment by duanchenggang** [comment]
Right. `2.0.8` hangs emacs, but HEAD works well.

Thank you.
