### ISSUE TITLE
Respect user key bindings

### ISSUE THREAD

**Issue by roysc** [ocaml/tuareg#39]
Key bindings prefixed with "C-c" are [reserved](https://www.gnu.org/software/emacs/manual/html_node/elisp/Key-Binding-Conventions.html) for user definitions.

The bindings currently on "C-c" in Tuareg mode should be bound to a new keymap. Users can then easily bind this new map to "C-c" (or anything else) using `define-prefix-command`.

**Comment by monnier** [comment]
> Key bindings prefixed with "C-c" are
> [reserved](https://www.gnu.org/software/emacs/manual/html_node/elisp/Key-Binding-Conventions.html)
> for user definitions.

Only C-c <letter> keybindings are reserved, not all C-c keybindings.


        Stefan

**Comment by roysc** [comment]
My mistake. I still think it would still be convenient to use a separate keymap but I will close for now.
