### ISSUE TITLE
Infinite loop

### ISSUE THREAD

**Issue by TontonJambon** [ocaml/tuareg#41]
Hello, it seems that tuareg causes my emacs to fall into infinite loop when I try to press tab in a .mll file, more precisely when I try to indent the parsing rules.

I hope this is a real bug and not just my computer being weird, and that I won't loose your time.

Thx a lot.

**Comment by Chris00** [comment]
On Wed, 1 Apr 2015 15:00:55 -0700, TontonJambon wrote:
> 
> Hello, it seems that tuareg causes my emacs to fall into infinite loop when I try to press tab in a .mll file, more precisely when I try to indent the parsing rules.

Could you post a specific example?  The latest version of tuareg (available in OPAM) does not activate it for .mll files.  A specific mode should be written for them — but I do not have time at the moment.

**Comment by Chris00** [comment]
No answer for 3 months, closing.
