### ISSUE TITLE
Installing from MELPA causes errors

### ISSUE THREAD

**Issue by kini** [ocaml/tuareg#44]
Well, one error, anyway. When installing tuareg from MELPA, I get the following message:

```
Compiling file /home/fs/.emacs.d/elpa/tuareg-20150316.1247/ocamldebug.el at Mon May  4 14:50:40 2015
Entering directory `/home/fs/.emacs.d/elpa/tuareg-20150316.1247/'
ocamldebug.el:42:1:Error: Cannot open load file: no such file or directory, /home/fs/.emacs.d/tuareg
```

This is on Emacs 24.4, with the [spacemacs](http://github.com/syl20bnr/spacemacs) configuration setup.

**Comment by Chris00** [comment]
This is not the latest version.  Could you please try to install it via `opam`?  An updated *melpa* package should be uploaded — do not know who contributed the first one.  If I have some time, I'll try to upload a more recent one (but if you want to contribute to this distribution channel, feel free to do it!).

**Comment by Chris00** [comment]
If you have a simple (if possible automated) recipe to update Tuareg on MELPA whenever a new version is released, please let me know.

**Comment by kini** [comment]
Unfortunately I don't actually know anything about ocaml or how to use opam. I was just trying to install tuareg because it was recommended to me in order to get syntax highlighting for a file I was trying to look at. I also don't know much about emacs packaging and I've never made a MELPA package myself! So I'm afraid I can't be of much help here, other than to simply report the issue I encountered :(

**Comment by Chris00** [comment]
It seems that MELPA sync. with this repository and bugs are [reported quickly](https://github.com/ocaml/tuareg/issues/104).  I thus guess the error reported here is solved.
