### ISSUE TITLE
PATH (compilation environment variable) gets corrupted when it contains spaces. 

### ISSUE THREAD

**Issue by lebotlan** [ocaml/tuareg#46]
If your PATH contains spaces, e.g. "/my directory/bin:/usr/bin:/bin", it gets corrupted when compiling with tuareg. It is trunkated at the first space.

The culprit is 'split-string' in  (defadvice compile...

(A pull request is coming to fix this).

**Comment by Chris00** [comment]
Does the above commit help?

**Comment by Chris00** [comment]
I did not notice your [PR](https://github.com/ocaml/tuareg/pull/47/files) before.  Please make a reference that it fixes the issue in your commit — so Github displays links and the issue gets closed upon merge.

**Comment by lebotlan** [comment]
Le 09/06/2015 23:56, Christophe Troestler a écrit :
> I did not notice your PR <https://github.com/ocaml/tuareg/pull/47/files>
> before. Please make a reference that it fixes the issue in your commit —
> so Github displays links and the issue gets closed upon merge.

OK. I was indeed looking for a way to link the PR and the bug report.
