### ISSUE TITLE
Function indentation

### ISSUE THREAD

**Issue by pveber** [ocaml/tuareg#5]
Version 2.0.8 indents function bodys the following way

```ocaml
let g x = h x ~f:(fun y ->
                  y + 1
                 )
```
while olders versions used to indent it this way:
```ocaml
let g x = h x ~f:(fun y ->
  y + 1
)
```
Is there a simple way to revert to the old behavior? Thanks!

**Comment by monnier** [comment]
I installed a patch that introduces a new config var tuareg-indent-align-with-first-arg which should let you express your preference for the "logf" example above.

**Comment by monnier** [comment]
Could you guys try the latest code and see how you like the result?  Some of the changes depend on a new (and undocumented :-( ) feature in Emacs-24.5, so make sure you try it in Emacs-24.5 (it should not break in older Emacsen, but it won't give the same indentation results).

I'll close this issue now, so if the result is not "good enough", please open a new issue.
