### ISSUE TITLE
cyclic-function-indirection tuareg-fontify

### ISSUE THREAD

**Issue by andreas-roehler** [ocaml/tuareg#53]
Activating trace messages this:

Debugger entered--Lisp error: (cyclic-function-indirection tuareg-fontify)
  indirect-function(tuareg-fontify)
  ad-real-orig-definition(tuareg-fontify)
  ad-make-advised-definition(tuareg-fontify)
  ad-activate-advised-definition(tuareg-fontify nil)
  ad-activate(tuareg-fontify nil)
  trace-function-internal(tuareg-fontify nil nil)
  trace-function(tuareg-fontify)
[ ... ]

**Comment by andreas-roehler** [comment]
In tuareg.el:

(defalias 'tuareg-fontify
    (eval-and-compile (if tuareg-use-syntax-ppss
                          'tuareg-ppss-fontify
                          'tuareg-!ppss-fontify)))
Where:

(defun tuareg-ppss-fontify (_beg _end) (error "tuareg uses PPSS"))

and tuareg-!ppss-fontify seems not defined.

**Comment by andreas-roehler** [comment]
Will fix this alongside.

**Comment by Chris00** [comment]
`tuareg-fontify` no longer exists.
