### ISSUE TITLE
Menu display real name

### ISSUE THREAD

**Issue by andreas-roehler** [ocaml/tuareg#55]
Would like to see the the real command name displayed too in menu. Also have same docu. WDYT?

**Comment by Chris00** [comment]
I do not understand what you mean.

**Comment by andreas-roehler** [comment]
Am 12.06.2015 um 00:14 schrieb Christophe Troestler:
>
> I do not understand what you mean.
>
> —
>

In case a command from menu is called, user might want to know, which 
one it was.

Displayed is only the tag-name for now. To do a C-h f for example, the 
real name is needed.

BTW have a script here to implement that, no hand-writing needed.

OTOH consider to postpone any work at menu until a decision is made WRT 
redundancy of navigation commands:

Switching to smie would break backward-compatibility to a certain extend 
and also XEmacs-compat.

What about making a release before?

**Comment by Chris00** [comment]
On Thu, 11 Jun 2015 22:48:32 -0700, Andreas Röhler wrote:
> 
> In case a command from menu is called, user might want to know, which
> one it was.
> 
> Displayed is only the tag-name for now.

Like all other menus

> To do a C-h f for example, the real name is needed.

That's what C-h k is for.

> Switching to smie would break backward-compatibility to a certain
> extend and also XEmacs-compat.

There are other identation options that SMIE can't handle at the
moment so providing only SMIE will not be done in the near future.

**Comment by andreas-roehler** [comment]
Am 12.06.2015 um 09:41 schrieb Christophe Troestler:
> On Thu, 11 Jun 2015 22:48:32 -0700, Andreas Röhler wrote:
> >
> > In case a command from menu is called, user might want to know, which
> > one it was.
> >
> > Displayed is only the tag-name for now.
>
> Like all other menus
>

Like _most_ would be correct.

Checking out python-mode.el might give an impression.

https://launchpad.net/python-mode


> > To do a C-h f for example, the real name is needed.
>
> That's what C-h k is for.
>
> > Switching to smie would break backward-compatibility to a certain
> > extend and also XEmacs-compat.
>
> There are other identation options that SMIE can't handle at the
> moment

As its BNF-approach is interesting, would like to have a closer look still.

May you tell me where it fails?

**Comment by Chris00** [comment]
> May you tell me where it fails?

https://github.com/ocaml/tuareg/issues/5

**Comment by andreas-roehler** [comment]
Am 12.06.2015 um 18:46 schrieb Christophe Troestler:
>
>     May you tell me where it fails?
>
> #5 <https://github.com/ocaml/tuareg/issues/5>
>
> —
>

Thanks. What about creating a smie-branch - while going on at trunk 
without it?
