### ISSUE TITLE
It's not clear for the installation documents.

### ISSUE THREAD

**Issue by KeyiChen** [ocaml/tuareg#58]
Im new to tuareg and Ocaml, and I found in file "tuareg.em", the comments said

;; Installation:
;; If you have permissions to the local `site-lisp' directory, you
;; only have to copy`tuareg.el', `tuareg_indent.el',`ocamldebug.el'
;; and `tuareg-site-file.el'.  Otherwise, copy the previous files
;; to a local directory and add the following line to your`.emacs':
;;
;; (add-to-list 'load-path "DIR")

My qstn is to install tuareg, don't we need to run "Makefile"? What does it mean by "copy the previous files to a local directory"? WHat's the name of local directory?

**Comment by Chris00** [comment]
Please use `opam install tuareg`.  I'll update the README.

**Comment by KeyiChen** [comment]
Thanks Christophe,

I configure the .emacs as documents told me but when I open emacs for MAC
OS, there is a (file-error "Cannot open load file" "tuareg-imenu")

And I remember there isnt any tuareg-imenu file resides in ~/tuareg/ and
~/.elisp/tuareg-mode/

Can you help me?

**Comment by Chris00** [comment]
On Mon, 15 Jun 2015 17:31:52 -0700, KeyiChen wrote:
> 
> I configure the .emacs as documents told me but when I open emacs for MAC OS, there is a (file-error "Cannot open load file" "tuareg-imenu")

Tuareg does not try to load tuareg-imenu.  Maybe you do in your own configuration files?

> And I remember there isnt any tuareg-imenu file resides in ~/tuareg/ and ~/.elisp/tuareg-mode/

If you installed using opam, they are in, say, ~/.opam/system/share/emacs/site-lisp/ (as indicated by the post-install message).

**Comment by KeyiChen** [comment]
Thanks for reply, yes im using opam and want to config emacs for Ocaml
programming.

Can you tell me where is the right path to file tuareg-imenu ?

**Comment by Chris00** [comment]
On Tue, 16 Jun 2015 10:32:06 -0700, KeyiChen wrote:
> 
> Can you tell me where is the right path to file tuareg-imenu ?

There is no tuareg-imenu coming with Tuareg.  There used ot be a 3rd party package named like that but I do not think it is maintained anymore.  You can use the speedbar to have a list of values and modules declared in a file (and jump to them).  I also recommend that you install merlin (via opam) alongside Tuareg.
