### ISSUE TITLE
Remove !ppss

### ISSUE THREAD

**Issue by Chris00** [ocaml/tuareg#59]
Providing a workaround for the absence of `syntax-ppss` (supported since the 15 years old Emacs 21 with the `syntax.el` add on) leads to code duplication for no good reason nowadays.  Syntax-ppss is currently not supported on the 6½ years old XEmacs 21.4.22 but the beta XEmacs 21.5.32, released in 2012, [has `syntax-ppss.el`](http://www.xemacs.org/Releases/21.5.32.html).  I think it should be removed.

**Comment by monnier** [comment]
I don't know where you can find the syntax.el add-on for Emacs-21, so I'd rather consider that syntax-ppss is only available since the 8 years old Emacs-22.  As for XEmacs, the version in Debian is still 21.4 with no sign that it will move on to 21.5 (at least not before there's an actual non-beta release, which seems oddly unlikely).

**Comment by monnier** [comment]
Of course, if you decide to remove support for emacsen without syntax-ppss, I'll be very happy to write the patch for it ;-)

**Comment by Chris00** [comment]
The  [Haskell mode](http://code.haskell.org/haskellmode-emacs/) uses [syntax.el](http://cvs.savannah.gnu.org/viewvc/emacs/emacs/lisp/emacs-lisp/syntax.el?view=log) from more recent Emacs versions.  If somebody complains, maybe a similar solution can be envisioned?

**Comment by monnier** [comment]
Ah, that's not a bad idea.  It might also work for XEmacs, if needed.  Should I go ahead and remove the conditional ppss stuff, then?

**Comment by Chris00** [comment]
On Wed, 17 Jun 2015 05:50:40 -0700, monnier wrote:
> 
> Ah, that's not a bad idea. It might also work for XEmacs, if needed. Should I go ahead and remove the conditional ppss stuff, then?

I think you can go on! ;-)

**Comment by monnier** [comment]
Done!
