### ISSUE TITLE
"let _" is needed to for `tuareg-eval-phrase`

### ISSUE THREAD

**Issue by brabalan** [ocaml/tuareg#60]
If I have the following buffer, with the point after the last `;;`
``` ocaml
let x = 12;;

print_endline "hello word!";;
```
when I type `C-x C-e` I get this as output:
```
# let x = 12;;
val x : int = 12
```
To actually evaluate the last phrase, I need to prefix it with `let _`.

Is this a misconfiguration on my side?

**Comment by Chris00** [comment]
I cannot reproduce your problem:
```ocaml
# let x = 12;;

print_endline "hello word!";;
val x : int = 12
#   hello word!
- : unit = ()
```

**Comment by brabalan** [comment]
I'm trying to debug this and here is what I see. The problem is that `tuareg--beginning-of-phrase` goes too far back.

The first iteration of `smie-backward-sexp` returns (18 11 ";;") and the point is at the beginning of `print_endline`. Since no condition applies (";;" is not in `tuareg-beginning-of-phrase-syms`, the return is not null, the first element is a number), then another iteration happens and the point goes to the first let, which is then executed.

**Comment by Chris00** [comment]
Now that I understood [what your report is about](https://github.com/ocaml/tuareg/issues/61), I am less keen to fix this one.  IMHO, code in a file should not use `;;` to delimit phrases — or rather, they can be present but the code should compile if they are all removed.

**Comment by brabalan** [comment]
Since this is in the context of teaching I'm trying to follow rigorous rules, such as http://ocaml.org/learn/tutorials/structure_of_ocaml_programs.html#Usingandomittingand
In particular, I try to minimize the difference between using the toplevel and using a file.

Here is a related bug, but without ";;". When evaluating the code
```
print_endline "hello world!"

let x = 5
```
with the point on the first line, and doing `C-x C-e`, the point ends up at the beginning of the quotes instead of the beginning of the let on the next line. So doing `C-x C-e` again does not evaluate the next phrase.

**Comment by Chris00** [comment]
IMHO, the rules given at http://ocaml.org/learn/tutorials/structure_of_ocaml_programs.html#Usingandomittingand are overly complicated and that section should be rewritten.  The *first* answer to “When should you use ;;” should be *to mark the end of an entry to the toploop* — and then one may go on explaining that it may *sometimes* be useful in code files too (but *not* to avoid executable blocks).

**Comment by brabalan** [comment]
I just noticed this has been fixed. Thanks!
