### ISSUE TITLE
top-level indentation

### ISSUE THREAD

**Issue by holocronweaver** [ocaml/tuareg#65]
Hello! I am new to OCaml, but have been using Emacs for a few years now. 

When I try to indent the following code in an otherwise empty source file in tuareg-mode:
```
let print_world () = print_endline "hello world" ;;
print_world () ;;
```
I get:
```
let print_world () = print_endline "hello world" ;;
  print_world () ;;
```
That seems strange to me. What is the logic behind indenting the second line. Shouldn't it be the same as the first?

**Comment by Chris00** [comment]
The double semicolon `;;` should not be used in `.ml` files to delimit executable statements.  Instead you should write:
```ocaml
let print_world () = print_endline "hello world"
let () = print_world ()
```
So, I think it is a good thing that the indentation of the second line looks odd! :-)
