### ISSUE TITLE
ocamldebug arguments when run from Emacs

### ISSUE THREAD

**Issue by dariusf** [ocaml/tuareg#66]
Is `ocamldebug` able to take arguments to the program it's stepping through when run from Emacs?

I modified it slightly to do so (using `read-from-minibuffer`) but am not sure if there's an existing/better way. If there isn't, I would also be happy to open a PR.

**Comment by Chris00** [comment]
Not that I am aware of.  A PR is welcome.

**Comment by Chris00** [comment]
Hope the way I did it will suit you.  (Quoted arguments are accepted so you can provide arguments with spaces.)

**Comment by dariusf** [comment]
Thanks!
