### ISSUE TITLE
helm(imenu?) support

### ISSUE THREAD

**Issue by moosotc** [ocaml/tuareg#67]
It would be very nice to have functioning helm-imenu in tuareg mode (FWIW it works fine in caml-mode). Currently executing `M-x imenu` when visiting buffer in tuareg-mode leads to "Scan error" message.

Debugger entered--Lisp error: (error "Scan error")
  signal(error ("Scan error"))
  error("Scan error")
  tuareg-imenu-create-index()
  imenu--make-index-alist()
  imenu-choose-buffer-index()
  byte-code("\300 C\207" [imenu-choose-buffer-index] 1)
  call-interactively(imenu record nil)
  command-execute(imenu record)
  execute-extended-command(nil "imenu" nil)
  funcall-interactively(execute-extended-command nil "imenu" nil)
  call-interactively(execute-extended-command nil nil)
  command-execute(execute-extended-command)

**Comment by monnier** [comment]
Can you try the patch below, to see if it helps?

    diff --git a/tuareg.el b/tuareg.el
    index 9bd6d95..a0cc488 100644
    --- a/tuareg.el
    +++ b/tuareg.el
    @@ -2487,6 +2493,12 @@ which `smie-backward-sexp' returns `nil'.")
     
       (defun tuareg--beginning-of-phrase ()
         (while
    +        (if (save-excursion
    +              (member (tuareg-smie-backward-token)
    +                      tuareg-beginning-of-phrase-syms))
    +            (progn
    +              (tuareg-smie-backward-token)
    +              nil)
             (let ((td (smie-backward-sexp 'halfsexp)))
               (cond
                ((member (nth 2 td) tuareg-beginning-of-phrase-syms)
    @@ -2500,7 +2512,7 @@ which `smie-backward-sexp' returns `nil'.")
                 nil)
                ((and (car td) (not (numberp (car td))))
                 (unless (bobp) (goto-char (nth 1 td)) t))
    -           (t t)))))
    +           (t t))))))
     
       (defun tuareg-discover-phrase (&optional _quiet _stop-at-and)
         "Return a triplet (BEGIN END END-WITH-COMMENTS)."
    @@ -2863,7 +2863,10 @@
           (goto-char (1+ (point)))          ;Don't signal error at EOB.
           (let ((old-point (point))
                 (last-and (progn (tuareg-next-phrase t t) (point))))
    -        (when (< last-and old-point) (error "Scan error"))
    +        (if (< last-and old-point)
    +            (progn
    +              (message "¡tuareg-next-phrase moved backward from %S!" old-point)
    +              (goto-char old-point))
             (save-excursion
               (while (and (re-search-backward "\\<and\\>" old-point t)
                           (not (tuareg-in-literal-or-comment-p))
    @@ -2871,7 +2874,7 @@
                           (save-excursion (tuareg-find-and-match)
                                           (>= old-point (point))))
                 (setq last-and (point))))
    -        (goto-char last-and)))
    +          (goto-char last-and))))
         (if (integerp cpt)
             (message "Searching definitions... done")
           (progress-reporter-done cpt))

**Comment by moosotc** [comment]
monnier <notifications@github.com> writes:

> Can you try the patch below, to see if it helps?
>

It almost works (for, let's call them, simpler sources). Enters some
kind of endless loop with:
https://github.com/moosotc/llpp/blob/master/main.ml though.

Debugger entered--Lisp error: (quit)
  (= 0 (skip-chars-backward "."))
  (and (= 0 (skip-chars-backward ".")) (= 0 (skip-syntax-backward ".")))
  (not (and (= 0 (skip-chars-backward ".")) (= 0 (skip-syntax-backward "."))))
  (while (not (and (= 0 (skip-chars-backward ".")) (= 0 (skip-syntax-backward ".")))))
  (cond ((memq (char-after) (quote (59 44))) nil) ((and (eq (char-after) 46) (memq (char-before) (quote (48 49 50 51 52 53 54 55 56 57 48)))) (skip-chars-backward "0-9")) (t (while (not (and (= 0 (skip-chars-backward ".")) (= 0 (skip-syntax-backward ".")))))))
  (if (and (= 0 (skip-chars-backward ".")) (= 0 (skip-syntax-backward "."))) (progn (skip-syntax-backward "w_'") (and (memq (char-before) (quote (45 43))) (memq (char-after) (quote (48 49 50 51 52 53 54 55 56 57 48))) (save-excursion (forward-char -1) (skip-syntax-backward "w_") (looking-at tuareg-smie--float-re)) (>= (match-end 0) (point)) (goto-char (match-beginning 0)))) (cond ((memq (char-after) (quote (59 44))) nil) ((and (eq (char-after) 46) (memq (char-before) (quote (48 49 50 51 52 53 54 55 56 57 48)))) (skip-chars-backward "0-9")) (t (while (not (and (= 0 (skip-chars-backward ".")) (= 0 (skip-syntax-backward "."))))))))
  (progn (if (and (= 0 (skip-chars-backward ".")) (= 0 (skip-syntax-backward "."))) (progn (skip-syntax-backward "w_'") (and (memq (char-before) (quote (45 43))) (memq (char-after) (quote (48 49 50 51 52 53 54 55 56 57 48))) (save-excursion (forward-char -1) (skip-syntax-backward "w_") (looking-at tuareg-smie--float-re)) (>= (match-end 0) (point)) (goto-char (match-beginning 0)))) (cond ((memq (char-after) (quote (59 44))) nil) ((and (eq (char-after) 46) (memq (char-before) (quote (48 49 50 51 52 53 54 55 56 57 48)))) (skip-chars-backward "0-9")) (t (while (not (and (= 0 ...) (= 0 ...))))))) (point))
  (buffer-substring-no-properties (point) (progn (if (and (= 0 (skip-chars-backward ".")) (= 0 (skip-syntax-backward "."))) (progn (skip-syntax-backward "w_'") (and (memq (char-before) (quote (45 43))) (memq (char-after) (quote (48 49 50 51 52 53 54 55 56 57 48))) (save-excursion (forward-char -1) (skip-syntax-backward "w_") (looking-at tuareg-smie--float-re)) (>= (match-end 0) (point)) (goto-char (match-beginning 0)))) (cond ((memq (char-after) (quote (59 44))) nil) ((and (eq (char-after) 46) (memq (char-before) (quote ...))) (skip-chars-backward "0-9")) (t (while (not (and ... ...)))))) (point)))
  tuareg-smie--backward-token()
  (setq tok (tuareg-smie--backward-token))
  (progn (setq tok (tuareg-smie--backward-token)) (if (not (= 0 (length tok))) (not (member tok tokens)) (if (bobp) nil (condition-case err (progn (backward-sexp) t) (scan-error (setq tok (buffer-substring (nth 3 err) (1+ ...))) nil)))))
  (while (progn (setq tok (tuareg-smie--backward-token)) (if (not (= 0 (length tok))) (not (member tok tokens)) (if (bobp) nil (condition-case err (progn (backward-sexp) t) (scan-error (setq tok (buffer-substring ... ...)) nil))))))
  (let (tok) (while (progn (setq tok (tuareg-smie--backward-token)) (if (not (= 0 (length tok))) (not (member tok tokens)) (if (bobp) nil (condition-case err (progn (backward-sexp) t) (scan-error (setq tok ...) nil)))))) tok)
  tuareg-smie--search-backward(("with" "|" "fun" "functor" "type" ":" "of"))
  (setq nearest (tuareg-smie--search-backward (quote ("with" "|" "fun" "functor" "type" ":" "of"))))
  (progn (setq nearest (tuareg-smie--search-backward (quote ("with" "|" "fun" "functor" "type" ":" "of")))) (and (equal nearest ":") (tuareg-smie--label-colon-p)))
  (while (progn (setq nearest (tuareg-smie--search-backward (quote ("with" "|" "fun" "functor" "type" ":" "of")))) (and (equal nearest ":") (tuareg-smie--label-colon-p))))
  (let (nearest) (while (progn (setq nearest (tuareg-smie--search-backward (quote ("with" "|" "fun" "functor" "type" ":" "of")))) (and (equal nearest ":") (tuareg-smie--label-colon-p)))) (if (member nearest (quote ("with" "|" "fun" "functor"))) tok "t->"))
  (save-excursion (let (nearest) (while (progn (setq nearest (tuareg-smie--search-backward (quote ("with" "|" "fun" "functor" "type" ":" "of")))) (and (equal nearest ":") (tuareg-smie--label-colon-p)))) (if (member nearest (quote ("with" "|" "fun" "functor"))) tok "t->")))
  (cond ((equal tok "let") (save-excursion (let ((prev (tuareg-smie--backward-token))) (if (or (member prev tuareg-smie--exp-leaders) (if (= 0 ...) (and ... ...) (and ... ...))) tok "d-let")))) ((member tok (quote ("module" "class" "open"))) (let ((prev (save-excursion (tuareg-smie--backward-token)))) (cond ((equal prev "let") (concat "l-" tok)) ((and (member prev (quote ...)) (equal tok "module")) "w-module") (t tok)))) ((equal tok "->") (save-excursion (let (nearest) (while (progn (setq nearest (tuareg-smie--search-backward ...)) (and (equal nearest ":") (tuareg-smie--label-colon-p)))) (if (member nearest (quote ("with" "|" "fun" "functor"))) tok "t->")))) ((equal tok "type") (save-excursion (let ((prev (tuareg-smie--backward-token))) (cond ((equal prev "module") "m-type") ((member prev (quote ...)) "w-type") (t tok))))) ((member tok (quote ("with" "and"))) (save-excursion (tuareg-smie--forward-token) (if (member (tuareg-smie--forward-token) (quote ("type" "module"))) (concat "m-" tok) tok))) ((equal tok "=") (tuareg-smie--=-disambiguate)) ((= 0 (length tok)) (if (not (and (memq (char-before) (quote (125 93))) (save-excursion (forward-char -2) (looking-at ">}\\||\\]")))) tok (goto-char (match-beginning 0)) (match-string 0))) ((and (equal tok "|") (eq (char-before) 91)) (forward-char -1) "[|") ((and (equal tok "<") (eq (char-before) 123)) (forward-char -1) "{<") ((memq (aref tok 0) (quote (42 47 37 43 45 64 94 61 60 62 124 38 36))) (cond ((member tok (quote ("|" "||" "&" "&&" "<-" "->"))) tok) ((and (eq (aref tok 0) 42) (> (length tok) 1) (eq (aref tok 1) 42)) "**…") (t (string (aref tok 0) 8230)))) ((equal tok ":") (let ((pos (point))) (if (tuareg-smie--label-colon-p) "label:" (goto-char pos) tok))) ((string-match "\\`[[:alpha:]_].*\\.\\'" tok) (forward-char (1- (length tok))) ".") (t tok))
  (let ((tok (tuareg-smie--backward-token))) (cond ((equal tok "let") (save-excursion (let ((prev (tuareg-smie--backward-token))) (if (or (member prev tuareg-smie--exp-leaders) (if ... ... ...)) tok "d-let")))) ((member tok (quote ("module" "class" "open"))) (let ((prev (save-excursion (tuareg-smie--backward-token)))) (cond ((equal prev "let") (concat "l-" tok)) ((and (member prev ...) (equal tok "module")) "w-module") (t tok)))) ((equal tok "->") (save-excursion (let (nearest) (while (progn (setq nearest ...) (and ... ...))) (if (member nearest (quote ...)) tok "t->")))) ((equal tok "type") (save-excursion (let ((prev (tuareg-smie--backward-token))) (cond ((equal prev "module") "m-type") ((member prev ...) "w-type") (t tok))))) ((member tok (quote ("with" "and"))) (save-excursion (tuareg-smie--forward-token) (if (member (tuareg-smie--forward-token) (quote ("type" "module"))) (concat "m-" tok) tok))) ((equal tok "=") (tuareg-smie--=-disambiguate)) ((= 0 (length tok)) (if (not (and (memq (char-before) (quote ...)) (save-excursion (forward-char -2) (looking-at ">}\\||\\]")))) tok (goto-char (match-beginning 0)) (match-string 0))) ((and (equal tok "|") (eq (char-before) 91)) (forward-char -1) "[|") ((and (equal tok "<") (eq (char-before) 123)) (forward-char -1) "{<") ((memq (aref tok 0) (quote (42 47 37 43 45 64 94 61 60 62 124 38 36))) (cond ((member tok (quote ("|" "||" "&" "&&" "<-" "->"))) tok) ((and (eq (aref tok 0) 42) (> (length tok) 1) (eq (aref tok 1) 42)) "**…") (t (string (aref tok 0) 8230)))) ((equal tok ":") (let ((pos (point))) (if (tuareg-smie--label-colon-p) "label:" (goto-char pos) tok))) ((string-match "\\`[[:alpha:]_].*\\.\\'" tok) (forward-char (1- (length tok))) ".") (t tok)))
  (lambda nil (let ((tok (tuareg-smie--backward-token))) (cond ((equal tok "let") (save-excursion (let ((prev ...)) (if (or ... ...) tok "d-let")))) ((member tok (quote ("module" "class" "open"))) (let ((prev (save-excursion ...))) (cond ((equal prev "let") (concat "l-" tok)) ((and ... ...) "w-module") (t tok)))) ((equal tok "->") (save-excursion (let (nearest) (while (progn ... ...)) (if (member nearest ...) tok "t->")))) ((equal tok "type") (save-excursion (let ((prev ...)) (cond (... "m-type") (... "w-type") (t tok))))) ((member tok (quote ("with" "and"))) (save-excursion (tuareg-smie--forward-token) (if (member (tuareg-smie--forward-token) (quote ...)) (concat "m-" tok) tok))) ((equal tok "=") (tuareg-smie--=-disambiguate)) ((= 0 (length tok)) (if (not (and (memq ... ...) (save-excursion ... ...))) tok (goto-char (match-beginning 0)) (match-string 0))) ((and (equal tok "|") (eq (char-before) 91)) (forward-char -1) "[|") ((and (equal tok "<") (eq (char-before) 123)) (forward-char -1) "{<") ((memq (aref tok 0) (quote (42 47 37 43 45 64 94 61 60 62 124 38 36))) (cond ((member tok (quote ...)) tok) ((and (eq ... 42) (> ... 1) (eq ... 42)) "**…") (t (string (aref tok 0) 8230)))) ((equal tok ":") (let ((pos (point))) (if (tuareg-smie--label-colon-p) "label:" (goto-char pos) tok))) ((string-match "\\`[[:alpha:]_].*\\.\\'" tok) (forward-char (1- (length tok))) ".") (t tok))))()
  smie-next-sexp((lambda nil (let ((tok (tuareg-smie--backward-token))) (cond ((equal tok "let") (save-excursion (let ((prev ...)) (if (or ... ...) tok "d-let")))) ((member tok (quote ("module" "class" "open"))) (let ((prev (save-excursion ...))) (cond ((equal prev "let") (concat "l-" tok)) ((and ... ...) "w-module") (t tok)))) ((equal tok "->") (save-excursion (let (nearest) (while (progn ... ...)) (if (member nearest ...) tok "t->")))) ((equal tok "type") (save-excursion (let ((prev ...)) (cond (... "m-type") (... "w-type") (t tok))))) ((member tok (quote ("with" "and"))) (save-excursion (tuareg-smie--forward-token) (if (member (tuareg-smie--forward-token) (quote ...)) (concat "m-" tok) tok))) ((equal tok "=") (tuareg-smie--=-disambiguate)) ((= 0 (length tok)) (if (not (and (memq ... ...) (save-excursion ... ...))) tok (goto-char (match-beginning 0)) (match-string 0))) ((and (equal tok "|") (eq (char-before) 91)) (forward-char -1) "[|") ((and (equal tok "<") (eq (char-before) 123)) (forward-char -1) "{<") ((memq (aref tok 0) (quote (42 47 37 43 45 64 94 61 60 62 124 38 36))) (cond ((member tok (quote ...)) tok) ((and (eq ... 42) (> ... 1) (eq ... 42)) "**…") (t (string (aref tok 0) 8230)))) ((equal tok ":") (let ((pos (point))) (if (tuareg-smie--label-colon-p) "label:" (goto-char pos) tok))) ((string-match "\\`[[:alpha:]_].*\\.\\'" tok) (forward-char (1- (length tok))) ".") (t tok)))) #[256 "\211\204\300\262\301[!\207" [1 forward-sexp] 3 1773790 "^p"] #<subr car> #[257 "\211A@\207" [] 2 2407115] halfsexp)
  smie-backward-sexp(halfsexp)
  (let ((td (smie-backward-sexp (quote halfsexp)))) (cond ((member (nth 2 td) tuareg-beginning-of-phrase-syms) (goto-char (nth 1 td)) nil) ((and (null td) (looking-back tuareg-beginning-of-phrase-syms-re (line-beginning-position))) (tuareg-smie-backward-token) nil) ((and (car td) (not (numberp (car td)))) (if (bobp) nil (goto-char (nth 1 td)) t)) (t t)))
  (if (save-excursion (member (tuareg-smie-backward-token) tuareg-beginning-of-phrase-syms)) (progn (tuareg-smie-backward-token) nil) (let ((td (smie-backward-sexp (quote halfsexp)))) (cond ((member (nth 2 td) tuareg-beginning-of-phrase-syms) (goto-char (nth 1 td)) nil) ((and (null td) (looking-back tuareg-beginning-of-phrase-syms-re (line-beginning-position))) (tuareg-smie-backward-token) nil) ((and (car td) (not (numberp (car td)))) (if (bobp) nil (goto-char (nth 1 td)) t)) (t t))))
  (while (if (save-excursion (member (tuareg-smie-backward-token) tuareg-beginning-of-phrase-syms)) (progn (tuareg-smie-backward-token) nil) (let ((td (smie-backward-sexp (quote halfsexp)))) (cond ((member (nth 2 td) tuareg-beginning-of-phrase-syms) (goto-char (nth 1 td)) nil) ((and (null td) (looking-back tuareg-beginning-of-phrase-syms-re (line-beginning-position))) (tuareg-smie-backward-token) nil) ((and (car td) (not (numberp ...))) (if (bobp) nil (goto-char (nth 1 td)) t)) (t t)))))
  tuareg--beginning-of-phrase()
  (save-excursion (end-of-line) (tuareg--beginning-of-phrase) (let ((begin (point))) (smie-forward-sexp (quote halfsexp)) (let ((end (point))) (forward-comment 5) (list begin end (point)))))
  tuareg-discover-phrase(t t)
  (nth 2 (tuareg-discover-phrase quiet stop-at-and))
  (save-excursion (nth 2 (tuareg-discover-phrase quiet stop-at-and)))
  (goto-char (save-excursion (nth 2 (tuareg-discover-phrase quiet stop-at-and))))
  tuareg-next-phrase(t t)
  (progn (tuareg-next-phrase t t) (point))
  (let ((old-point (point)) (last-and (progn (tuareg-next-phrase t t) (point)))) (if (< last-and old-point) (progn (message "¡tuareg-next-phrase moved backward from %S!" old-point) (goto-char old-point)) (save-excursion (while (and (re-search-backward "\\<and\\>" old-point t) (not (tuareg-in-literal-or-comment-p)) (save-excursion (tuareg-find-and-match) (>= old-point (point)))) (setq last-and (point)))) (goto-char last-and)))
  (while (not (eobp)) (if (looking-at tuareg-definitions-regexp) (progn (setq kw (tuareg-match-string 0)) (let ((save-match-data-internal (match-data))) (unwind-protect (progn (tuareg-reset-and-kwop kw)) (set-match-data save-match-data-internal (quote evaporate)))) (if (member kw (quote ("exception" "val"))) (progn (setq kw "let"))) (goto-char (match-end 0)) (tuareg-skip-blank-and-comments) (if (looking-at tuareg-definitions-bind-skip-regexp) (progn (goto-char (match-end 0)))) (tuareg-skip-blank-and-comments) (if (looking-at tuareg-identifier-regexp) (progn (let ((ref ...)) (if (not ...) (progress-reporter-update cpt ...) (setq cpt ...) (message "Searching definitions... (%d)" cpt)) (cond (... ...) (... ...) (... ...) (... ...) (t ...))))))) (goto-char (1+ (point))) (let ((old-point (point)) (last-and (progn (tuareg-next-phrase t t) (point)))) (if (< last-and old-point) (progn (message "¡tuareg-next-phrase moved backward from %S!" old-point) (goto-char old-point)) (save-excursion (while (and (re-search-backward "\\<and\\>" old-point t) (not (tuareg-in-literal-or-comment-p)) (save-excursion (tuareg-find-and-match) (>= old-point ...))) (setq last-and (point)))) (goto-char last-and))))
  (let ((cpt (if (fboundp (quote make-progress-reporter)) (make-progress-reporter "Searching definitions..." (point-min) (point-max)) 0)) (kw) (value-list) (type-list) (module-list) (class-list) (misc-list)) (goto-char (point-min)) (tuareg-skip-blank-and-comments) (while (not (eobp)) (if (looking-at tuareg-definitions-regexp) (progn (setq kw (tuareg-match-string 0)) (let ((save-match-data-internal (match-data))) (unwind-protect (progn (tuareg-reset-and-kwop kw)) (set-match-data save-match-data-internal (quote evaporate)))) (if (member kw (quote ("exception" "val"))) (progn (setq kw "let"))) (goto-char (match-end 0)) (tuareg-skip-blank-and-comments) (if (looking-at tuareg-definitions-bind-skip-regexp) (progn (goto-char (match-end 0)))) (tuareg-skip-blank-and-comments) (if (looking-at tuareg-identifier-regexp) (progn (let (...) (if ... ... ... ...) (cond ... ... ... ... ...)))))) (goto-char (1+ (point))) (let ((old-point (point)) (last-and (progn (tuareg-next-phrase t t) (point)))) (if (< last-and old-point) (progn (message "¡tuareg-next-phrase moved backward from %S!" old-point) (goto-char old-point)) (save-excursion (while (and (re-search-backward "\\<and\\>" old-point t) (not ...) (save-excursion ... ...)) (setq last-and (point)))) (goto-char last-and)))) (if (integerp cpt) (message "Searching definitions... done") (progress-reporter-done cpt)) (let ((index nil)) (if module-list (progn (setq index (cons (cons "Modules" module-list) index)))) (if type-list (progn (setq index (cons (cons "Types" type-list) index)))) (if class-list (progn (setq index (cons (cons "Classes" class-list) index)))) (if value-list (progn (setq index (cons (cons "Values" value-list) index)))) (if misc-list (progn (setq index (cons (cons "Miscellaneous" misc-list) index)))) index))
  tuareg-imenu-create-index()
  imenu--make-index-alist()
  imenu-choose-buffer-index()
  byte-code("\300 C\207" [imenu-choose-buffer-index] 1)
  call-interactively(imenu record nil)
  command-execute(imenu record)
  execute-extended-command(nil "imenu" nil)
  funcall-interactively(execute-extended-command nil "imenu" nil)
  call-interactively(execute-extended-command nil nil)
  command-execute(execute-extended-command)

And the *Messages* buffer is filled with:
¡tuareg-next-phrase moved backward from <number>!

-- 
mailto:moosotc@gmail.com

**Comment by monnier** [comment]
Install further change to try and fix this problem.  The imenu scanning code is still rather brittle and inefficient (especially with lots of "and"), but in any case the scanning is *much* faster with `tuareg-use-smie` than without, so in terms of fixing regressions I think we're no worse than before now.

**Comment by moosotc** [comment]
monnier <notifications@github.com> writes:

> Install further change to try and fix this problem.  The imenu
> scanning code is still rather brittle and inefficient (especially with
> lots of "and"), but in any case the scanning is *much* faster with
> `tuareg-use-smie` than without, so in terms of fixing regressions I
> think we're no worse than before now.
>

Yes, that does fix this particular issue, thank you. That said, it feels
like under tuareg, unlike caml, rescanning takes place every time
helm-imenu is called [1].

[1] Unlike plain imenu where there's no rescanning.

-- 
mailto:moosotc@gmail.com

**Comment by moosotc** [comment]
monnier <notifications@github.com> writes:

> Install further change to try and fix this problem.  The imenu
> scanning code is still rather brittle and inefficient (especially with
> lots of "and"), but in any case the scanning is *much* faster with
> `tuareg-use-smie` than without, so in terms of fixing regressions I
> think we're no worse than before now.
>

Not sure if I should open separate issue or continue here, in any case,
here goes:

imenu under tuareg lists possible categories:
*Rescan* 	Classes
Modules 	Values

while with caml:
*Rescan* 	Classes 	Index
Methods 	Modules 	Values

And those Index/Methods that tuareg lacks are quite useful for (at
least) code bases with classes/objects.

-- 
mailto:moosotc@gmail.com

**Comment by monnier** [comment]
Regarding helm-imenu, I don't know why it rescans all the time, sorry.
And as for the difference between caml's imenu and tuareg's imenu, I'm not sure what should be done about it.  I guess Christophe should chime in (I'm mostly interested in the indentation code and the use of SMIE for parsing).  Part of the question here is "why do we have 2 major modes": should we simply rely more in caml's package (e.g. reuse its imenu support)?  I started using Tuareg many years ago, when its indentation and font-lock support was much better (at least for my use cases) than caml.el's, but in general it'd be better for the two projects to try and share their work, rather than duplicate it.

**Comment by moosotc** [comment]
monnier <notifications@github.com> writes:

> Regarding helm-imenu, I don't know why it rescans all the time, sorry.
> And as for the difference between caml's imenu and tuareg's imenu, I'm
> not sure what should be done about it.  I guess Christophe should
> chime in (I'm mostly interested in the indentation code and the use of
> SMIE for parsing).  Part of the question here is "why do we have 2
> major modes": should we simply rely more in caml's package (e.g. reuse
> its imenu support)?  I started using Tuareg many years ago, when its
> indentation and font-lock support was much better (at least for my use
> cases) than caml.el's, but in general it'd be better for the two
> projects to try and share their work, rather than duplicate it.
>

I too switched to tuareg many years ago, for the reasons that I can not
reliably recall right now. And the point worth making is this: tuareg
and caml do indent things differently so switching is not really all
that easy/transparent, truth be told tuareg I've used for decades (in X
not FSF Emacs) indents things differntly than the current (but the
result is much closer than that of caml-mode). In any case thanks for
the help.

-- 
mailto:moosotc@gmail.com

**Comment by Chris00** [comment]
Imenu now uses the code in the standard OCaml mode — which is kept in sync with the evolution of the language.

**Comment by Pitometsu** [comment]
UPD: FYI https://github.com/ocaml/tuareg/issues/101#issuecomment-456047677
