### ISSUE TITLE
Whole buffer is not highlighted

### ISSUE THREAD

**Issue by hectorpal** [ocaml/tuareg#68]
I just updated from tuareg 1.5 to 2.09, and also updated the caml-modes files.

Now the whole buffer is not highlighted as before. Using font-lock-fontify-buffer makes the trick for the area around the cursor, but if I move around, it is not highlighted.
Font-lock documentation say:
"To fontify a buffer, without turning on Font Lock mode and regardless of buffer
size, you can use M-x font-lock-fontify-buffer"
but it's not not highlighting "regardless of buffer size".

BTW, I put the .el and .elc in my local site-lisp,
and the only relevant line to ocaml in my .emacs is 
(load "/home/me/local/site-lisp/tuareg-site-file.el")

Aquamacs 3.2 GNU Emacs 24.4.51.2
(x86_64-apple-darwin14.0.0, NS apple-appkit-1343.14)
 of 2014-11-07 (Aquamacs-3.2) on watson.local
OS X Captain.

**Comment by Chris00** [comment]
What is your font-lock configuration in `~/.emacs` or `~/.emacs.d/init.el`?

**Comment by hectorpal** [comment]
There were a few lines requiring or setting global-font-lock-mode. I commented all references/ocurrences of font-lock. The problems continue. 
Now I'm trying under Ubuntu 14.04. If I switch back to previous .el, the highlight is done correct.

I tried now with an smaller consisting on 65 copies of this code:

```
let f () =
  if 0 == 1 then
    f()
```

**Comment by hectorpal** [comment]
Ok, I deleted all the .elc files and is highlighting correct now. The .elc were generated not by script but through a free interpretation of the Makefile. Actually, I copied to ~/local/site-lisp all .el and .elc in both caml-mode-4.02 and tuareg-2.0.9. I don't have neither marmelade or opam, and I wasn't sure how to install it.
If I don't comment tomorrow, it means the problem is also solved for Aquamacs under OS X.
Thanks.

**Comment by Chris00** [comment]
The problem on MacOS is that it comes with a old version of Emacs and Aquamacs does not put a newer version in the PATH.  There is a tentative workaround looking for `/Applications/Emacs.app/Contents/MacOS/Emacs` but it may not be fit for Aquamacs.  What is its path?

**Comment by hectorpal** [comment]
The error was definitively corrected in OS X (Aquamas) after deleting the .elc I created following the instructions of the Makefile. thanks

**Comment by Chris00** [comment]
What is full path of the Aquamacs executable that may be used on the command line?

**Comment by hectorpal** [comment]
Aquamacs is in /Applications/Aquamacs.app,
but as I said the problem was totally solved in both emacs/linux and aquamacs/osx after I deleted the .elc files I generated by hand following the Makefile. Maybe I made a mistake.

**Comment by Chris00** [comment]
Installing Tuareg through opam did not byte compile the files (it will from now on... but not on Darwin!).  Was there anything that made you issue `make elc`?

**Comment by hectorpal** [comment]
I don't remember. Make failed, so a looked up the target all, and maybe misunderstood the OS dependent parts. Thanks.
