### ISSUE TITLE
Module return with signature indentation

### ISSUE THREAD

**Issue by AeroNotix** [ocaml/tuareg#7]
Consider the following:

``` Ocaml
module Make_comp(C : Comparitor) : Comparitor_intf with type t := C.t =
                                                                    struct
                                                                      type t = C.t
                                                                      let ret = C.comp
                                                                    end
```

The struct portion should not be indented all the way over there :)

**Comment by Chris00** [comment]
The syntax of `with type` and `with module` is explained at http://caml.inria.fr/pub/docs/manual-ocaml/modtypes.html — the `=` can be `:=` (this is an [extension](http://caml.inria.fr/pub/docs/manual-ocaml/extn.html#sec234)).

**Comment by Chris00** [comment]
There is still a problem (the `and` indentation) with
```ocaml
module Make_comp(C : Comparitor) : Comparitor_intf
       with type t := C.t
                  and module X = Z =
  struct
    type t = C.t
    let ret = C.comp
  end
```

**Comment by Chris00** [comment]
@monnier As always, your input is very welcome! 😊

**Comment by monnier** [comment]
How 'bout

    diff --git a/tuareg.el b/tuareg.el
    index 65c246a..b16e3b9 100644
    --- a/tuareg.el
    +++ b/tuareg.el
    @@ -1652,6 +1652,23 @@ Return values can be
                  (member (tuareg-smie--backward-token) '("with" "and"))) "c=")
            (t "d=")))))
     
    +(defun tuareg-smie--:=-disambiguate ()
    +  "Return which kind of \":=\" we've just found.
    +Point is not moved and should be right in front of the equality.
    +Return values can be
    +  \":=\" for assignment definition,
    +  \"c=\" for destructive equlity constraint."
    +  (save-excursion
    +    (let* ((pos (point))
    +           (telltale '("type" "let" "module" "class" "and" "external"
    +                       "val" "method" "DEFINE" "=" ":="
    +                       "if" "then" "else" "->" ";" ))
    +           (nearest (tuareg-smie--search-backward telltale)))
    +      (cond				;Issue #7
    +       ((and (member nearest '("type" "module"))
    +             (member (tuareg-smie--backward-token) '("with" "and"))) "c=")
    +       (t ":=")))))
    +
     (defun tuareg-smie--|-or-p ()
       "Return non-nil if we're just in front of an or pattern \"|\"."
       (save-excursion
    @@ -1728,6 +1745,7 @@ Return values can be
          ;; Distinguish a defining = from a comparison-=.
          ((equal tok "=")
           (tuareg-smie--=-disambiguate))
    +     ((equal tok ":=") (tuareg-smie--:=-disambiguate))
          ((zerop (length tok))
           (if (not (and (memq (char-before) '(?\} ?\]))
                         (save-excursion (forward-char -2)

**Comment by Chris00** [comment]
We can distinguish various `:=` but what about
```ocaml
module Make(C : C) : D
       with type t = C.t = struct
  ...
end
```

**Comment by Chris00** [comment]
Thanks.
