### ISSUE TITLE
clean up documentation

### ISSUE THREAD

**Issue by agarwal** [ocaml/tuareg#70]
Here are various things making it currently difficult to start with tuareg:
- [x] README says "see tuareg.el" for usage, but `tuareg.el` provides hardly any information on usage.
- [x] Both `tuareg.el` and `tuareg-site-file.el` say that there is a `dot-emacs.el` file provided as a sample customization, but I can't find any such file. This would indeed be very useful for the next couple of points.
- [x] Explain how to work with `ocp-indent`. Does tuareg explicitly support ocp-indent? If we're using ocp-indent, are all the tuareg indentation customizations irrelevant, or somehow still have an effect.
- [x] Explain how merlin works with tuareg. I have merlin working, but I'm unsure if tuareg interacts with merlin specifically, or if all functionality of these two are unrelated.
- [ ] Document all the customizations possible. From various sources I know of lots of things that can be configured, but I don't see any explanation of these in the repo.

BTW, I've used tuareg for years just fine. I'm prompted to learn it better right now because for some reason indentation has gone haywire over the last couple of months (as pointed out by others in #69, #71, #72). I have no idea why.

**Comment by Chris00** [comment]
For `ocp-indent`, the [page of the tool](http://www.typerex.org/ocp-indent.html) explains how to install it.  Tuareg has its own indentation engine and does not require that tool.  Granted, the move to SMIE has generated some surprises but these are ironed out.  I am thankful to @monnier for the time he spent porting Tuareg to SMIE.

The lack of documentation just reflects my lack of time.  I'll try to fix that.  If there are customizations that you use (or would like to have), please report them!

**Comment by agarwal** [comment]
> For ocp-indent, the page of the tool explains how to install it.

Yes, I have ocp-indent installed and enabled.

> Tuareg has its own indentation engine and does not require that tool.

Right, that much was also clear.

What I don't know is how ocp-indent and tuareg's builtin engine interact. Does tuareg detect that ocp-indent is active, and so disable its builtin engine? The specific problem I'm having is that ocp-indent's configurations don't seem to have any effect. So of course I can start debugging and isolating the issue, and learn more elisp, and so on, but I feel this kind of information should just be said.

> the move to SMIE has generated some surprises

Yes, I eventually disabled SMIE and electric indentation. For the benefit of others, do this in your emacs file:

```elisp
(electric-indent-mode -1)
(setq tuareg-use-smie nil)
```

With these disabled, things are better, but I still have some behavior that differs from how it used to be 2 months ago.

And of course thank you for all the hard work. You know I like to complain about documentation issues, and I still wonder how to motivate people to document more. Perhaps consider the amount of time you're spending answering all of my questions.  :)  Would it be less time to write documentation?

Quibble: The README says "To deactivate it, add (setq tuareg-use-smie nil) to the top-level of your .emacs file." I find the statement cryptic because it begs the question of why you're telling me to deactivate a feature that was just added and supposedly an improvement. A simple additional sentence could help, like "the SMIE engine is not yet well tested and the behavior may differ from before". If that is indeed the reason, but who knows until you tell us.

**Comment by Chris00** [comment]
> Does tuareg detect that ocp-indent is active, and so disable its builtin engine?

No.  I do not use `ocp-indent` so that part should be contributed by others.

> disabled SMIE and electric indentation. 

Emacs ≥ 24.4 enabled electric indentation by default.  I mentioned how to disable it in the README.

As for SMIE, I would recommend **not** to disable it and try the SMIE mode.  Most of the complains have been answered.  The old indentation engine will not be updated any more and will not stay for ever.  I tried to make the paragraph about that clearer — it was written in a haste after we enabled SMIE by default.

> Perhaps consider the amount of time you're spending answering all of my questions. :) Would it be less time to write documentation?

Unfortunately, I am a slow writer so the answer would tend to be negative... :-(

I have pushed an improved README — but it is not complete yet.

**Comment by agarwal** [comment]
Okay, thanks for all the answers. I'll try SMIE again, and report the issues I'm having if not already reported.

**Comment by agarwal** [comment]
>> Does tuareg detect that ocp-indent is active, and so disable its builtin engine?
> No.

So I'm still confused what does happen. Do the two engines fight over which is going to handle indentation? Does whichever one I enabled later take over? Maybe it's a general Emacs question. If anyone knows, please say so. Thanks.

**Comment by Chris00** [comment]
On Fri, 6 Nov 2015 05:30:46 -0800, Ashish Agarwal wrote:
> 
> Okay, thanks for all the answers. I'll try SMIE again, and report the issues I'm having if not already reported.

Please try the version under Git as it fixes several things you would like to have.  I intend to make a new release in the near future but do not hold your breath.

**Comment by Chris00** [comment]
A simple configuration for Merlin is in the [dot-emacs.el](https://github.com/ocaml/tuareg/blob/master/dot-emacs.el) file.

**Comment by Chris00** [comment]
@agarwal I think most important configuration possibilities are described in the README and the dot-emacs.el file (more options will be added in the future depending on requests).  Is there anything more you would like?

**Comment by agarwal** [comment]
Thank you! There might be a specific questions that still arise, but I think the broad request of this issue is resolved. Thus, I'll close it.
