### ISSUE TITLE
Use special indentation for begin match

### ISSUE THREAD

**Issue by Chris00** [ocaml/tuareg#73]
Due to open nature of the `match` construction, if is sometimes written as
```ocaml
    begin match n with
          | 0 -> ...
          | n -> ...
    end
```
It would be nice if this code was indented as if the `begin ... end` construction was not present:
```ocaml
    begin match n with
    | 0 -> ...
    | n -> ...
    end
```

**Comment by Chris00** [comment]
See also http://caml.inria.fr/mantis/view.php?id=6327

**Comment by Chris00** [comment]
And https://github.com/ocaml/ocaml/pull/278#issuecomment-154067639

**Comment by monnier** [comment]
This should hopefully be fixed now

**Comment by Chris00** [comment]
Thanks!
