### ISSUE TITLE
match clause indentation (with subclauses)

### ISSUE THREAD

**Issue by Chris00** [ocaml/tuareg#78]
Tuareg indents the following

``` ocaml
let x = match y, z with
  | A, (B | C)
  | X, Y -> do_something()
```

as

``` ocaml
let x = match y, z with
  | A, (B | C)
    | X, Y -> do_something()
```

**Comment by monnier** [comment]
Looks right to me: the last "|" is the pipe of an or-pattern rather than the pipe of a new branch.
IOW the above is parsed as

    let x = match y, z with
      | (A, (B | C)
         | X, Y) -> do_something()

and the indentation reflects this fact.

**Comment by Chris00** [comment]
I see your point.  I was surprised because that's not the way we are used to indent this.  Have to live with this for a while and see whether it improves the readability or is rather a "distraction".

**Comment by monnier** [comment]
If needed you should be able to get the other behavior with an smie rule like:

    (:before "|-or")  ==>  (if (smie-rule-parent-p "|") (smie-rule-parent))

**Comment by Chris00** [comment]
What remains to be done: make it possible to opt-out this indentation behavior (and possibly describe it in the README).

**Comment by monnier** [comment]
Doesn't the rule I provided on 20 Nov 2015 offer exactly the possibility to "opt-out"?

**Comment by Chris00** [comment]
@monnier It does — I'm slow as time is a scare resource on my side... :-(
