### ISSUE TITLE
defadvice compile & tramp & remote compilation

### ISSUE THREAD

**Issue by delamonpansie** [ocaml/tuareg#79]
Adding advice to compile breaks tramp compilation on remote targets without opam.

**Comment by moosotc** [comment]
Same issue here:
[quote]
-*- mode: compilation; default-directory: "/sshx:user@address:/path/" -*-
Compilation started at Sat Aug  6 02:43:59

make
env: sh: /usr/bin/zsh: No such file or directory: No such file or directory

Compilation exited abnormally with code 127 at Sat Aug  6 02:44:00
[end quote]

Following bandaid helps:
(add-hook 'tuareg-mode-hook
          (function (lambda ()
                      (ad-deactivate 'compile))))

**Comment by monnier** [comment]
There's no usable info in here.

**Comment by Chris00** [comment]
I think I understand what @delamonpansie means.  I'll take a look ASAP.

**Comment by moosotc** [comment]
monnier <notifications@github.com> writes:

> There's no usable info in here.
>

What constitutes usable info?

Here are the details of the setup:
 Machine A ("client", emacs runs here):
         1. Linux
         2. Has opam, shell is zsh (/usr/bin/zsh)

 Machine B ("host", sources live there and compilation should be done
            on this remote host):
         1. macOS
         2. No opam, shell is zsh (/usr/local/bin/zsh)

Makefile(or something non tuareg controlled) was opened via tramp:

         (find-file "/sshx:user@host:/Users/user/path/Makefile")
         (compile)

         Things work.

tuareg-mode file is opened using the same method:
         (find-file "/sshx:user@host:/Users/user/path/source.ml")
         (compile)

         Things fail in a fashion describe in the original message.

tuareg.el (when tuareg-opam) evaluates some things locally and then in
"compile" advice tries to set remote environment based on this local
info, that is the rooot of the problem (I think).

I guess the usability of original message lies in the work-around that
disables compilation advice.

-- 
mailto:moosotc@gmail.com

**Comment by moosotc** [comment]
moosotc@gmail.com writes:

> monnier <notifications@github.com> writes:
>
>> There's no usable info in here.
>>
>

FWIW the whole advice can be a source of confusion even without tramp,
because `compile` will do two different things if launched with/without
advice being installed, i.e. visiting some tuareg controlled file will
result in "opam way" (if it was detected) otherwise, say compile was
invoked within same directory, but no ocaml file was visited prior to
this (advice was never activated) - compilation will take entirely
different route.

[..snip..]

-- 
mailto:moosotc@gmail.com

**Comment by Chris00** [comment]
Without this advice, compiling in Emacs may take a different route than compiling in the shell after an `opam switch` which IMHO is even more problematic.  Maybe we can push something to `tuareg-site-file.el` so that compiling also loads `tuareg-mode`?

**Comment by monnier** [comment]
> Without this advice, compiling in Emacs may take a different route than
> compiling in the shell after an `opam switch` which IMHO is even more
> problematic.

Hmm... I'm not sure I understand.
So you're saying you do "opam switch" in a shell somewhere and Emacs
should behave differently after that?

What's the relationship between Emacs and this shell?


        Stefan

**Comment by Chris00** [comment]
Unless I do not remember well, `compile` runs in the environment provided by Emacs which is the environment in which Emacs was launched.  So `opam switch` is not detected.  This is a problem because when you move from one project to another, a different compiler version may be needed.  Or you want to test your code with various compiler versions while benefiting from Emacs help for debugging.

`opam switch` has a global effect—so no relation between Emacs and the shell where the switch takes place is needed.  (Opam 2 may behave differently, I can investigate.)

**Comment by Chris00** [comment]
@delamonpansie @moosotc May you be more specific on the kind of problem you encounter.  I tried to compile (`ocamlc ...`) a file on a remote machine and i did _not_ encounter a problem.

**Comment by moosotc** [comment]
Christophe Troestler <notifications@github.com> writes:

> @delamonpansie @moosotc May you be more specific on the kind of
> problem you encounter.  I tried to compile (`ocamlc ...`) a file on a
> remote machine and i did _not_ encounter a problem.
>

(when tuareg-opam
  (setq tuareg-interactive-program
        (concat tuareg-opam " config exec -- ocaml"))

Is done on the local machine that is the root of the problem. Issues:
    a. shells might be different (the case here
       /usr/bin/zsh vs /usr/local/bin/zsh)
    b. local machine might have opam while the remote one might not
       (again the case here)

I guess you can reproduce it by creating a fresh user on remote machine
and not install opam for him. Or create fresh user on the local machine
and chsh his shell to something that doesn't exist on the remote one.

-- 
mailto:moosotc@gmail.com

**Comment by delamonpansie** [comment]
Unable to reproduce. But advice tuareg-compile-opma is still wrong, variable tuareg-opam should be computed for each remote host independently. Call to the (shell-command-to-string) still produces an error, however this error no longer break (compile)

**Comment by moosotc** [comment]
Yuriy Vostrikov <notifications@github.com> writes:

> Unable to reproduce. But advice tuareg-compile-opma is still wrong,
> variable tuareg-opam should be computed for each remote host
> independently. Call to the (shell-command-to-string) still produces an
> error, however this error no longer break (compile)
>

You are unable to reproduce it with different shells (and/or lack of
opam on the target machine)? I'm rather surprised then.

-- 
mailto:moosotc@gmail.com

**Comment by delamonpansie** [comment]
I redo test on machine without opam. Calling opam on this machine expectedly fails and (shell-command-to-string get-env) returns error message "/bin/bash: /home/mon/bin/opam: No such file or directory\n". This error message then erroneously parsed as valid opam output and assigned to  'compilation-environment.

I guess that behavior of shell-command-to-string depends on something. In some cases it returns error as string, in other case it fails and breaks compilation.

**Comment by Chris00** [comment]
The current dev version of Tuareg only activates the advice if `tuareg-opam-insinuate` is `t` (default: `nil`).  I still have to work on the best course of action for this but at least the reported problem should no longer be triggered by default.
