### ISSUE TITLE
Wrong highlighted positions in ocamldebug

### ISSUE THREAD

**Issue by Chris00** [ocaml/tuareg#80]
[This message](https://sympa.inria.fr/sympa/arc/caml-list/2015-11/msg00169.html) says that the locations of errors were not correctly highlighted, possibly because of the presence of UTF8 comments.

**Comment by ttamttam** [comment]
Here is a small repro case with some explanations. It is not about errors, but simply highlighted source code in ocamldebuger mode. I do not think this is related to tuareg, is it?

File `unicode_program.ml`:
```OCaml
(* OCaml parser accepts only latin1 encoded code. I'm fine with that,
   and I'm used to encode unicode string literals using escape
   sequences.

   But in comments, it is extremely convenient to use unicode
   chars. *)


let function_that_should_be_ok i j k =
  let m = i + j in
  let n = m + k in
  n

    (* When using unicode in comments, for exemple :

       AC ⟂ BD

       or

       x ∈ ℚ

       in debuging mode, following functions are shifted. This is
       certainly due to the fact that ocamldebug should locate code
       fragments in bytes, while emacs is using chars?
     *)

let function_not_ok i j k =
  let m = i + j in
  let n = m + k in
  n

let main () =
  function_that_should_be_ok 1 2 3 (* when stepping into this function, highlighted fragments are OK *)
  |> function_not_ok 4 5                   (* but they are shifted below the comments that contains UTF-8 chars *)
  |> print_int

let () = main ()
```

and an `.ocamldebug`:
```
step
break @ Unicode_program 33
run
```

Salutations

**Comment by ttamttam** [comment]
[ocamldebug.txt](https://github.com/ocaml/tuareg/files/737440/ocamldebug.txt)
[unicode_program.txt](https://github.com/ocaml/tuareg/files/737441/unicode_program.txt)

**Comment by Chris00** [comment]
Thanks.

> This is certainly due to the fact that ocamldebug should locate code fragments in bytes, while emacs is using chars?

I think so too.
@monnier Is there a way for Emacs to go to the char part of the nth byte of a file?

**Comment by Chris00** [comment]
Replying to myself: `byte-to-position` is what it needed.

**Comment by Chris00** [comment]
@ttamttam Was it with the standard OCaml mode or with Tuareg?  It seems to me that, with Tuareg, it works fine.

**Comment by ttamttam** [comment]
I opened my source file from emacs. It loaded tuareg mode. From there, I ran M-x ocamldebug and selected
unicode_program.d.byte.

The debugging windows has OCaml-Debugger:run, and the source code has Tuareg utop Merlin modes.
This is with tuareg 2.0.10 (opam installation, ocaml 4.03.0 switch).

**Comment by ttamttam** [comment]
In debug mode, if I insert the right number of spaces in source code after each unicode char, the hilighted  code fragments are well located.

**Comment by Chris00** [comment]
With Emacs 25 and the devel version of Tuareg, I get:
![ocamldebug1](https://cloud.githubusercontent.com/assets/1255665/22404615/e977538e-e634-11e6-8f75-0e81a641d3cf.png)

**Comment by Chris00** [comment]
After a few `step`s, I have:

![ocamldebug2](https://cloud.githubusercontent.com/assets/1255665/22404626/212d1354-e635-11e6-8e89-89d8ba07664f.png)

**Comment by Chris00** [comment]
I guess this because of the [following commit](https://github.com/ocaml/tuareg/commit/27b2330e9ebe4841345a668fd05ef4e989b88b2d).

**Comment by ttamttam** [comment]
I tried with the dev version of tuareg. You are right: this bug is solved!
Sorry for the time you spent on this.

**Comment by Chris00** [comment]
It's not your fault I did not make the link sooner! 😊

Thanks for your prompt responses.

**Comment by monnier** [comment]
Guys, I'm sorry: while my crystal ball told me you were going to hit this bug, it failed to give me the issue-number you'd use for it, so I couldn't refer to it in the commit.  Also, Github did not let me close the bug, arguing that you hadn't opened it yet.  Damn those stupid tools!
I promise I'll try to do better next time.

**Comment by ttamttam** [comment]
Yes, please, correct in advance the next one I'll hit !

:-)

Le 29 janv. 2017 19:06, "monnier" <notifications@github.com> a écrit :

Guys, I'm sorry: while my crystal ball told me you were going to hit this
bug, it failed to give me the issue-number you'd use for it, so I couldn't
refer to it in the commit. Also, Github did not let me close the bug,
arguing that you hadn't opened it yet. Damn those stupid tools!
I promise I'll try to do better next time.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/ocaml/tuareg/issues/80#issuecomment-275933095>, or mute
the thread

**Comment by Chris00** [comment]
>it failed to give me the issue-number ... arguing that you hadn't opened it yet

@monnier I was not trying to blame you in any way and I am really happy with the time you spend and the quality of the code you write for Tuareg.  I apologize if I upset you.  I take the blame for not seeing that this issue was already solved when I decided to attack it.  I feel the need to set the record straight however — sorry, I am a mathematician after all — date([this issue](https://github.com/ocaml/tuareg/issues/80)) < date([commit](https://github.com/ocaml/tuareg/commit/27b2330e9ebe4841345a668fd05ef4e989b88b2d)).

**Comment by monnier** [comment]
Oh my god!  So my crystal ball lied to me!  And here I was thinking I really had a magic object able to predict the future.  What a rip off!  Oh well, at least now I know.  Thanks Chris!
