### ISSUE TITLE
Error utop-setup-ocaml-buffer' is deprecated

### ISSUE THREAD

**Issue by nscott32** [ocaml/tuareg#81]
Hello,
I alays have error "utop-setup-ocaml-buffer' is deprecated, you need to replace it by utop-minor-mode" when launching tuareg mode, what is annoying is that I can't run a service daemon with scratch buffer set to tuareg since the error makes the service fails.
How can I fix this ?

**Comment by Chris00** [comment]
There are no `utop*` functions in Tuareg.  You should tell more about your setup.

**Comment by Chris00** [comment]
I can't fix it without more information.  Please reopen if needed.
