### ISSUE TITLE
Regexp bug when looking for the end of a phrase

### ISSUE THREAD

**Issue by cstolze** [ocaml/tuareg#82]
Tuareg believes the end of the phrase "let f x_ = x_" is right before the last underscore, ie it tries to evaluate "let f x_ = x;;"

**Comment by Chris00** [comment]
To make sure I understand you: you have
```ocaml
let f x_ = x_
```
in a file, you pressed <kbd>C-c C-e</kbd> and expect (rightly) that phrase to be evaluated in the toplevel.

@cstolze Do you have SMIE enabled?  (I.e., on recent versions off Tuareg, you did __not__ put `(setq tuareg-use-smie nil)` in your Init File.)  Indeed, it works for me.

**Comment by cstolze** [comment]
The bug has been fixed a few days ago.

I have closed the bug.
