### ISSUE TITLE
No output from C function (Ctypes)

### ISSUE THREAD

**Issue by marktua** [ocaml/tuareg#83]
In tuareg mode, the output of C functions used via Ctypes is not visible in the emacs buffer. Consider the following toplevel snippet.

``` ocaml
# open Ctypes ;;
# let puts = Foreign.foreign "puts" (string @-> returning int) ;;
val puts : string -> int = <fun>
# puts "hello";;
- : int = 6
# print_endline "hello" ;;
hello
- : unit = ()
```

How can this be fixed?

**Comment by Chris00** [comment]
On Sat, 2 Apr 2016 09:57:42 -0700, marktua wrote:
> 
> # let puts = Foreign.foreign "puts" (string @-> returning int) ;;
> val puts : string -> int = <fun>
> # puts "hello";;
> - : int = 6
> # print_endline "hello" ;;
> hello
> - : unit = ()
> 
> How can this be fixed?

I doubt this has anything to do with Tuareg.  When you execute "puts", the string is copied to the C stdout buffer which is not the same as the OCaml one.  Did you try with calling C "fflush"?

**Comment by marktua** [comment]
I wrote the following C function, put it into a shared library, loaded it using
```ocaml
Dl.dlopen ~filename:"./mylib.so" ~flags:[Dl.RTLD_LAZY; Dl.RTLD_GLOBAL]
```
and called hello via Ctypes. The effect is the same, i.e. there is no output in the tuareg emacs buffer.
``` c
#include <stdio.h>
void hello(void)
{
  printf("hello\n");
  fflush(stdout);
}
```
Is there a way for tuareg to get hold of this output?

**Comment by Chris00** [comment]
It seems it is due to the fact that the process communicate with Emacs through a pipe.  It seems to work if I change it to a pipe.

**Comment by Chris00** [comment]
If you are in a hurry, try https://github.com/Chris00/tuareg
