### ISSUE TITLE
recent commits prevents detection of file mode

### ISSUE THREAD

**Issue by agarwal** [ocaml/tuareg#84]
One of the commits after 8c3f604ad3b393403baaa93fc53898217e675ab8 causes the following message upon opening an ml file:

```
File mode specification error: (void-variable balanced-braces-no-end-colon)
```

**Comment by Chris00** [comment]
On Fri, 8 Apr 2016 11:05:45 -0700, Ashish Agarwal wrote:
> 
> One of the commits after 8c3f604 causes the following message upon opening an
> ml file:
> 
> File mode specification error: (void-variable balanced-braces-no-end-colon)

You're right, I forgot to commit that part... :-(
