### ISSUE TITLE
Wrong newline handling within `{| ... |}` strings

### ISSUE THREAD

**Issue by nv-vn** [ocaml/tuareg#85]
In OCaml, delimited strings do not use escape characters. Consider the following toplevel code:

```ocaml
# "x
   y
   z";; (* Normal string *)
- : string = "x\ny\nz"
# {|x
   y
   z|};; (* Delimited *)
- : string = "x\ny\nz"
# "x\
   y\
   z";; (* With escapes *)
- : string = "xyz"
# {|x\
   y\
   z|} (* Delimited with escapes *)
- : string = "x\\\ny\\\nz"
```

Since the escapes are not evaluated (and the string is used verbatim), when a backslash is present it not only keeps the newline, but also introduces a backslash into the resulting string. In tuareg-mode, `\` is inserted every time a newline is created inside of a string literal (both normal or delimited). However, in delimited strings this causes an extra backslash to be present in the final string (which is usually not the intended effect). Instead, it would make more sense for tuareg to only insert the backslash in non-delimited strings.

**Comment by Chris00** [comment]
> In tuareg-mode, \ is inserted every time a newline is created inside of a string literal

No, not for me.  Are you sure it is not the effect of some option that you set (globally thinking of it) for another mode?

**Comment by nv-vn** [comment]
Hm, at least looking through `tuareg_indent.el`, it seems that [this](https://github.com/ocaml/tuareg/blob/master/tuareg_indent.el#L1712-L1728) is where it would be happening. Running `M-x tuareg-newline-and-indent` in emacs causes the backslash to be added into the string literal. I can't think of an option that would be affecting this, although I may be missing something.

**Comment by Chris00** [comment]
Got it.  You should really use SMIE mode or submit a PR for the old indentation mode.

**Comment by nv-vn** [comment]
Weird, I do have SMIE enabled (`tuareg-use-smie` is set to `t`). I could try with a new .emacs and see what happens.

**Comment by nv-vn** [comment]
Interesting... seems to work correctly on a fresh install. Since the old indentation mode is already deprecated, I don't think it's necessary to add to it but if I can't get it working after I work on the fresh install I will submit a PR.
