### ISSUE TITLE
Problem with struct and sig

### ISSUE THREAD

**Issue by disteph** [ocaml/tuareg#86]
indent-test.ml shows, on lines 1195-1197:
```
module Base64 : sig
  val f : int -> int
end
```
and the preamble of the file says "the indentation code does find this indentation".
However, having installed tuareg 2.0.9 from opam, the above code gets indented as follows:
```
module Base64 : sig
    val f : int -> int
  end
```
(the 2nd and 3rd lines are 2 spaces too deep)
I don't think I changed any of the default options. By disabling the SMIE implementation with (setq tuareg-use-smie nil), I get the correct behaviour though.

**Comment by Chris00** [comment]
On 2016-06-08, Stéphane Graham-Lengrand wrote:
> 
> indent-test.ml shows, on lines 1195-1197:
> 
> module Base64 : sig
>   val f : int -> int
> end
> 
> and the preamble of the file says "the indentation code does find this
> indentation".
> However, having installed tuareg 2.0.9 from opam, the above code gets 
> indented
> as follows:
> 
> module Base64 : sig
>     val f : int -> int
>   end
> 
> (the 2nd and 3rd lines are 2 spaces too deep)
> I don't think I changed any of the default options. By disabling the 
> SMIE
> implementation with (setq tuareg-use-smie nil), I get the correct 
> behaviour
> though.

This has been fixed in the master branch.  I'll try to make a release 
ASAP.

**Comment by disteph** [comment]
Great, thanks! (including for your rapid response)

**Comment by Chris00** [comment]
Release [pending](https://github.com/ocaml/opam-repository/pull/6715).
