### ISSUE TITLE
Phrase not evaluated with camlp4o

### ISSUE THREAD

**Issue by ysalmon** [ocaml/tuareg#87]
I am using tuareg 2.0.10 with ocaml 4.02.3 (from opam).
I am encountering a problem with the following code : 
```ocaml
#use "topfind";;
#camlp4o;;

type machin = {x: float; y:float};;

let a = {x=2.0; y=2.0};;
```

When evaluating this phrases successively in Emacs (C-c C-e), I get stuck with the last one. The toplevel echoes back ```let a = {x=2.0; y=2.0};;``` but there is no answer. When I stumble upon this problem in bigger programs, I can sometimes evaluate the function containing the offending expression by C-c C-e at multiple places within its code, but then the interaction with the toplevel becomes inconsistent (it seems that excerpts of phrases are evaluated).

This problem does not occur if camlp4o is not loaded.

I am opening an issue here and not at camlp4 because this really seems related to the interaction provided by tuareg. Saving the aforementioned program in a ```/tmp/test.ml``` and then evaluating in emacs/tuareg the phrases
```ocaml
#use "topfind";;
#camlp4o;;

#use "/tmp/test.ml";;
a;;
```
works correctly.

**Comment by Chris00** [comment]
Thanks for the bug report.  However, it is not specific to Tuareg.  Typing the same commands in the toplevel launched in a shell gives the same outcome:
```ocaml
 ocaml -noinit
        OCaml version 4.03.0

# #use "topfind";;
- : unit = ()
Findlib has been successfully loaded. Additional directives:
  #require "package";;      to load a package
  #list;;                   to list the available packages
  #camlp4o;;                to load camlp4 (standard syntax)
  #camlp4r;;                to load camlp4 (revised syntax)
  #predicates "p,q,...";;   to set these predicates
  Topfind.reset();;         to force that packages will be reloaded
  #thread;;                 to enable threads

- : unit = ()
# #camlp4o;; 
/home/trch/.opam/4.03.0/lib/ocaml/dynlink.cma: loaded
/home/trch/.opam/4.03.0/lib/ocaml/camlp4: added to search path
/home/trch/.opam/4.03.0/lib/ocaml/camlp4/camlp4o.cma: loaded
	Camlp4 Parsing version 4.03.0

# type machin = {x: float; y:float};;
type machin = { x : float; y : float; }
# let a = {x=2.0; y=2.0};;
```
I believe you should report the issue to [camlp4](https://github.com/ocaml/camlp4).

**Comment by ysalmon** [comment]
That's right ; I am sorry I did not think to check this (since the ```#use``` trick worked, I assumed that everything was fine there).

Issue ocaml/camlp4#107 is opened.
