### ISSUE TITLE
  (load "path-to-git-checkout-dir/tuareg-site-file")

### ISSUE THREAD

**Issue by jasonhe89** [ocaml/tuareg#93]
The below describe has a typo,

"If you want to install from the Git checkout, just add to your ~/.emacs or ~/.emacs.d/init.el the line:

(load "path-to-git-checkout-dir/tuareg-site-file")"

(load "path-to-git-checkout-dir/tuareg-site-file") should be (loadfile "path-to-git-checkout-dir/tuareg-site-file") on mac os.

**Comment by monnier** [comment]
Why do you think so?

**Comment by jasonhe89** [comment]
I tried (load "path-to-git-checkout-dir/tuareg-site-file") on my mac emacs, but my emacs can't evaluate the expression. After I changed load to loadfile, my emacs worked. I don't know why. Maybe something related the way I install tuareg?

**Comment by Chris00** [comment]
Is it the [standard Emacs](https://www.gnu.org/software/emacs/) or a [special](http://aquamacs.org/) [version for OSX](https://emacsformacosx.com/)?  (Ideally, that should not change anything.)

**Comment by monnier** [comment]
Please describe what you mean by "can't evaluate the expression": what did you do and what did Emacs do in return.

**Comment by Chris00** [comment]
Can't fix it without more information.  Please reopen if needed.
