### ISSUE TITLE
Breaks all compilation on newer opam (in a difficult-to-track way)

### ISSUE THREAD

**Issue by AltGr** [ocaml/tuareg#94]
[here](https://github.com/ocaml/tuareg/blob/1e68a0addca6165b8f1cadfcd15c0b7ef5184e9a/tuareg.el#L2390), `opam config env` is called and its output parsed. This is wrong, and opam 2.0 changed its shell-directed output format to use single instead of double quotes (protecting against double-evaluation), which leads to values for _e.g._ `PATH` including the quotes and triggers weird errors.

I am not sure tuareg should take care of updating the compilation-environment anyway ; but if this feature is to be kept for now, `opam config env --sexp`, which is intended for that purpose and won't break, should be called instead. [here](https://github.com/OCamlPro/opam-user-setup/blob/7c574c0618bd5b155b8211ff6319c4cc10caf810/emacs/emacs.ml#L144-L154) is an example using `shell-command-to-string` then `read-from-string`

**Comment by Drup** [comment]
My personal grain of salt (as the one who got hit by that thing): tuareg should really not do that, `opam user-setup` does it better and in a more reliable way. 
Please make tuareg not mess with merlin, opam, the PATH, or any of the other tool, it's just painful.

**Comment by AltGr** [comment]
@Chris00 can something be done about this ? Otherwise I'll have to add a patch on the opam repo (or fork) before I can push forward the opam dev release. Thanks

**Comment by Chris00** [comment]
I'll try ro fix this ASAP.
