### ISSUE TITLE
"Wrong type argument: listp, ERROR" when using compile command in emacs

### ISSUE THREAD

**Issue by william3** [ocaml/tuareg#97]
It comes from this code : 

  ;; OPAM compilation — one must update to the current compiler
  ;; before launching the compilation.
  (defadvice compile (before tuareg-compile-opam activate)
      "Run opam to update environment variables."
      (set (make-local-variable 'compilation-environment)
           (mapcar (lambda (b) (concat (car b) "=" (cadr b)))
                   (tuareg-opam-config-env))))

I dowloaded last version for 4.03.0+flambda, it points to tuareg 2.0.10, but browsing the code I did not find the related part... ?

Best regards

**Comment by william3** [comment]
ok, the difference comes from a patch in opam !
Anyway, what is the rational in making this command just don't call "compile", creating a dependance on opam ?

**Comment by Chris00** [comment]
Thanks for the report.  I'll make the advice on compiling opt-in only.  However, I find a bit strange that the it was triggered as Tuareg checks for the presence of `opam`.  What is the value of the variable `tuareg-opam` (`C-h v tuareg-opam`) on the other machine?

**Comment by ysalmon** [comment]
For reference, this (and https://github.com/ocaml/tuareg/commit/b1b68427d271aac0aaf0f40f187e6ad52b920819) is the reason why the out-of-the-box prompt for OCaml executable does not show ```/usr/bin/opam config exec -- ocaml``` anymore but ```ocaml```.

**Comment by Chris00** [comment]
You need to set `tuareg-opam-insinuate` to `t` for that.

Note that you can use `tuareg-opam-update-env` to update the Emacs environment from the opam one and `ocaml` will be searched according to it.
